/* Generated by cbindgen from harfbuzz_subset_c_api. Do not edit by hand. */

#ifndef HARFRUST_SUBSET_H
#define HARFRUST_SUBSET_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>
#include "hr.h"

/**
 * Subsetting configuration, owning its glyph and Unicode sets.
 *
 * Mutation requires exclusive access. Returned sets are borrowed; take a
 * set reference if it must outlive this input.
 */
typedef struct hr_subset_input_t hr_subset_input_t;

typedef unsigned int hr_subset_flags_t;

/**
 * All supported subset flags are unset.
 */
#define HR_SUBSET_FLAGS_DEFAULT 0

/**
 * Remove TrueType hinting instructions.
 */
#define HR_SUBSET_FLAGS_NO_HINTING 1

/**
 * Keep original glyph IDs, leaving holes for removed glyphs.
 */
#define HR_SUBSET_FLAGS_RETAIN_GIDS 2

/**
 * Preserve the outline of glyph zero.
 */
#define HR_SUBSET_FLAGS_NOTDEF_OUTLINE 64

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates a subset input with empty glyph and Unicode selections.
 *
 * As in the shaping C API, Rust allocation failure aborts the process.
 */
struct hr_subset_input_t *hr_subset_input_create_or_fail(void);

/**
 * Takes another reference to a live input. `NULL` stays `NULL`.
 *
 * # Safety
 * `input` must be `NULL` or live.
 */
struct hr_subset_input_t *hr_subset_input_reference(struct hr_subset_input_t *input);

/**
 * Releases an input reference and its owned sets. Accepts `NULL`.
 *
 * # Safety
 * `input` must be `NULL` or an owned reference.
 */
void hr_subset_input_destroy(struct hr_subset_input_t *input);

/**
 * Returns the borrowed set of glyph IDs to retain, or `NULL` for no input.
 *
 * # Safety
 * `input` must be `NULL` or live; the returned set is borrowed from it.
 */
hr_set_t *hr_subset_input_glyph_set(struct hr_subset_input_t *input);

/**
 * Returns the borrowed set of Unicode codepoints to retain.
 *
 * # Safety
 * `input` must be `NULL` or live; the returned set is borrowed from it.
 */
hr_set_t *hr_subset_input_unicode_set(struct hr_subset_input_t *input);

/**
 * Sets the subset flags. Unsupported flag bits cause subsetting to fail.
 *
 * # Safety
 * `input` must be `NULL` or live and exclusively accessible.
 */
void hr_subset_input_set_flags(struct hr_subset_input_t *input, unsigned int flags);

/**
 * Returns the configured flags, or zero for `NULL`.
 *
 * # Safety
 * `input` must be `NULL` or live and not concurrently mutated.
 */
hr_subset_flags_t hr_subset_input_get_flags(const struct hr_subset_input_t *input);

/**
 * Subsets a face with skera, returning a new face with serialized SFNT data.
 *
 * Returns `NULL` for invalid input, unsupported flags or outline formats,
 * missing table enumeration, or skera failure. The original face and input
 * are unchanged. Rust panics in the subsetter are contained at this boundary.
 *
 * # Safety
 * `face` and `input` must be `NULL` or live. Neither the input nor its sets
 * may be modified during the call. Face callbacks must satisfy HarfRust's
 * threading contract.
 */
hr_face_t *hr_subset_or_fail(hr_face_t *face, const struct hr_subset_input_t *input);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* HARFRUST_SUBSET_H */
