[package]
name = "harfrust-capi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "C API for the HarfRust text shaping library, mirroring HarfBuzz's shaping API."
repository.workspace = true
license.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
harfrust = { workspace = true, features = ["std", "experimental_font_api"] }
read-fonts.workspace = true

[lib]
name = "harfrust_c"
crate-type = ["staticlib", "cdylib", "rlib"]
bench = false

[lints]
workspace = true
