/* Generated by cbindgen from harfrust_capi/src/draw.rs. */

#ifndef HARFRUST_DRAW_H
#define HARFRUST_DRAW_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "hr.h"

/**
 * A reference-counted, optionally immutable collection of draw callbacks.
 */
typedef struct hr_draw_funcs_t hr_draw_funcs_t;

/**
 * Drawing state. Its layout matches HarfBuzz, including private reserved words.
 */
typedef struct hr_draw_state_t {
  hr_bool_t path_open;
  float path_start_x;
  float path_start_y;
  float current_x;
  float current_y;
  uint32_t reserved[7];
} hr_draw_state_t;

/**
 * Callback for move to; data must be safe to use on any thread.
 */
typedef void (*hr_draw_move_to_func_t)(struct hr_draw_funcs_t *funcs,
                                       void *draw_data,
                                       struct hr_draw_state_t *st,
                                       float to_x,
                                       float to_y,
                                       void *user_data);

/**
 * Callback for line to; data must be safe to use on any thread.
 */
typedef void (*hr_draw_line_to_func_t)(struct hr_draw_funcs_t *funcs,
                                       void *draw_data,
                                       struct hr_draw_state_t *st,
                                       float to_x,
                                       float to_y,
                                       void *user_data);

/**
 * Callback for quadratic to; data must be safe to use on any thread.
 */
typedef void (*hr_draw_quadratic_to_func_t)(struct hr_draw_funcs_t *funcs,
                                            void *draw_data,
                                            struct hr_draw_state_t *st,
                                            float control_x,
                                            float control_y,
                                            float to_x,
                                            float to_y,
                                            void *user_data);

/**
 * Callback for cubic to; data must be safe to use on any thread.
 */
typedef void (*hr_draw_cubic_to_func_t)(struct hr_draw_funcs_t *funcs,
                                        void *draw_data,
                                        struct hr_draw_state_t *st,
                                        float control1_x,
                                        float control1_y,
                                        float control2_x,
                                        float control2_y,
                                        float to_x,
                                        float to_y,
                                        void *user_data);

/**
 * Callback for close path; data must be safe to use on any thread.
 */
typedef void (*hr_draw_close_path_func_t)(struct hr_draw_funcs_t *funcs,
                                          void *draw_data,
                                          struct hr_draw_state_t *st,
                                          void *user_data);

/**
 * Legacy callback, assumed to succeed.
 */
typedef void (*hr_font_draw_glyph_func_t)(hr_font_t *font,
                                          void *font_data,
                                          hr_codepoint_t glyph,
                                          struct hr_draw_funcs_t *funcs,
                                          void *draw_data,
                                          void *user_data);

/**
 * Custom glyph-outline callback. Returns true if the glyph was drawn.
 */
typedef hr_bool_t (*hr_font_draw_glyph_or_fail_func_t)(hr_font_t *font,
                                                       void *font_data,
                                                       hr_codepoint_t glyph,
                                                       struct hr_draw_funcs_t *funcs,
                                                       void *draw_data,
                                                       void *user_data);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates an owned callback collection.
 */
struct hr_draw_funcs_t *hr_draw_funcs_create(void);

/**
 * Returns the immortal empty collection.
 */
struct hr_draw_funcs_t *hr_draw_funcs_get_empty(void);

/**
 * Takes a reference. Accepts NULL.
 */
struct hr_draw_funcs_t *hr_draw_funcs_reference(struct hr_draw_funcs_t *funcs);

/**
 * Releases an owned reference and its callback data. Accepts NULL.
 */
void hr_draw_funcs_destroy(struct hr_draw_funcs_t *funcs);

/**
 * Rejects subsequent callback changes.
 */
void hr_draw_funcs_make_immutable(struct hr_draw_funcs_t *funcs);

/**
 * Reports whether callback changes are forbidden.
 */
hr_bool_t hr_draw_funcs_is_immutable(const struct hr_draw_funcs_t *funcs);

/**
 * Attaches address-keyed metadata, taking ownership only on success.
 */
hr_bool_t hr_draw_funcs_set_user_data(struct hr_draw_funcs_t *funcs,
                                      const hr_user_data_key_t *key,
                                      void *data,
                                      hr_destroy_func_t destroy,
                                      hr_bool_t replace);

/**
 * Returns borrowed metadata.
 */
void *hr_draw_funcs_get_user_data(const struct hr_draw_funcs_t *funcs,
                                  const hr_user_data_key_t *key);

/**
 * Registers move to. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_draw_funcs_set_move_to_func(struct hr_draw_funcs_t *funcs,
                                    hr_draw_move_to_func_t func,
                                    void *user_data,
                                    hr_destroy_func_t destroy);

/**
 * Registers line to. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_draw_funcs_set_line_to_func(struct hr_draw_funcs_t *funcs,
                                    hr_draw_line_to_func_t func,
                                    void *user_data,
                                    hr_destroy_func_t destroy);

/**
 * Registers quadratic to. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_draw_funcs_set_quadratic_to_func(struct hr_draw_funcs_t *funcs,
                                         hr_draw_quadratic_to_func_t func,
                                         void *user_data,
                                         hr_destroy_func_t destroy);

/**
 * Registers cubic to. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_draw_funcs_set_cubic_to_func(struct hr_draw_funcs_t *funcs,
                                     hr_draw_cubic_to_func_t func,
                                     void *user_data,
                                     hr_destroy_func_t destroy);

/**
 * Registers close path. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_draw_funcs_set_close_path_func(struct hr_draw_funcs_t *funcs,
                                       hr_draw_close_path_func_t func,
                                       void *user_data,
                                       hr_destroy_func_t destroy);

/**
 * Begins a contour, closing any open contour. Move callbacks are emitted lazily.
 */
void hr_draw_move_to(struct hr_draw_funcs_t *funcs,
                     void *data,
                     struct hr_draw_state_t *st,
                     float to_x,
                     float to_y);

/**
 * Adds a line, opening a contour when needed.
 */
void hr_draw_line_to(struct hr_draw_funcs_t *funcs,
                     void *data,
                     struct hr_draw_state_t *st,
                     float to_x,
                     float to_y);

/**
 * Adds a cubic Bezier segment.
 */
void hr_draw_cubic_to(struct hr_draw_funcs_t *funcs,
                      void *data,
                      struct hr_draw_state_t *st,
                      float c1x,
                      float c1y,
                      float c2x,
                      float c2y,
                      float to_x,
                      float to_y);

/**
 * Adds a quadratic segment, converting to cubic when no quadratic callback exists.
 */
void hr_draw_quadratic_to(struct hr_draw_funcs_t *funcs,
                          void *data,
                          struct hr_draw_state_t *st,
                          float cx,
                          float cy,
                          float to_x,
                          float to_y);

/**
 * Closes a contour, emitting its final line before close when needed.
 */
void hr_draw_close_path(struct hr_draw_funcs_t *funcs, void *data, struct hr_draw_state_t *st);

/**
 * Sets a custom outline callback. Takes ownership of its data even when rejected.
 */
void hr_font_funcs_set_draw_glyph_func(hr_font_funcs_t *ffuncs,
                                       hr_font_draw_glyph_func_t func,
                                       void *user_data,
                                       hr_destroy_func_t destroy);

/**
 * Sets a custom outline callback returning success.
 */
void hr_font_funcs_set_draw_glyph_or_fail_func(hr_font_funcs_t *ffuncs,
                                               hr_font_draw_glyph_or_fail_func_t func,
                                               void *user_data,
                                               hr_destroy_func_t destroy);

/**
 * Draws an unhinted glyph using Skrifa, or the installed font callback.
 * Supported outlines are glyf, CFF, CFF2, and VARC. Returns false on invalid input.
 * All pointers must be NULL or live; callbacks must not mutate the font or funcs.
 */
hr_bool_t hr_font_draw_glyph_or_fail(hr_font_t *font,
                                     hr_codepoint_t glyph,
                                     struct hr_draw_funcs_t *funcs,
                                     void *draw_data);

/**
 * Compatibility entry point ignoring the success result.
 */
void hr_font_draw_glyph(hr_font_t *font,
                        hr_codepoint_t glyph,
                        struct hr_draw_funcs_t *funcs,
                        void *draw_data);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* HARFRUST_DRAW_H */

#define HR_DRAW_STATE_DEFAULT {0, 0.f, 0.f, 0.f, 0.f, {0}}
