/* Generated by scripts/gen-hb-compat-header.py. Do not edit by hand. */
#ifndef HARFRUST_HB_SUBSET_H
#define HARFRUST_HB_SUBSET_H
#include "hr-hb.h"
#include "hr-subset.h"

/* Types, functions and callbacks */

#define hb_face_t                      hr_face_t
#define hb_set_t                       hr_set_t
#define hb_subset_flags_t              hr_subset_flags_t
#define hb_subset_input_create_or_fail hr_subset_input_create_or_fail
#define hb_subset_input_destroy        hr_subset_input_destroy
#define hb_subset_input_get_flags      hr_subset_input_get_flags
#define hb_subset_input_glyph_set      hr_subset_input_glyph_set
#define hb_subset_input_reference      hr_subset_input_reference
#define hb_subset_input_set_flags      hr_subset_input_set_flags
#define hb_subset_input_t              hr_subset_input_t
#define hb_subset_input_unicode_set    hr_subset_input_unicode_set
#define hb_subset_or_fail              hr_subset_or_fail

/* Constants and macros */

#define HB_SUBSET_FLAGS_DEFAULT        HR_SUBSET_FLAGS_DEFAULT
#define HB_SUBSET_FLAGS_NOTDEF_OUTLINE HR_SUBSET_FLAGS_NOTDEF_OUTLINE
#define HB_SUBSET_FLAGS_NO_HINTING     HR_SUBSET_FLAGS_NO_HINTING
#define HB_SUBSET_FLAGS_RETAIN_GIDS    HR_SUBSET_FLAGS_RETAIN_GIDS

#endif /* HARFRUST_HB_SUBSET_H */
