/* Generated by scripts/gen-hb-compat-header.py. Do not edit by hand. */
#ifndef HARFRUST_HB_DRAW_H
#define HARFRUST_HB_DRAW_H
#include "hr-hb.h"
#include "hr-draw.h"

/* Types, functions and callbacks */

#define hb_bool_t                                 hr_bool_t
#define hb_codepoint_t                            hr_codepoint_t
#define hb_destroy_func_t                         hr_destroy_func_t
#define hb_draw_close_path                        hr_draw_close_path
#define hb_draw_close_path_func_t                 hr_draw_close_path_func_t
#define hb_draw_cubic_to                          hr_draw_cubic_to
#define hb_draw_cubic_to_func_t                   hr_draw_cubic_to_func_t
#define hb_draw_funcs_create                      hr_draw_funcs_create
#define hb_draw_funcs_destroy                     hr_draw_funcs_destroy
#define hb_draw_funcs_get_empty                   hr_draw_funcs_get_empty
#define hb_draw_funcs_get_user_data               hr_draw_funcs_get_user_data
#define hb_draw_funcs_is_immutable                hr_draw_funcs_is_immutable
#define hb_draw_funcs_make_immutable              hr_draw_funcs_make_immutable
#define hb_draw_funcs_reference                   hr_draw_funcs_reference
#define hb_draw_funcs_set_close_path_func         hr_draw_funcs_set_close_path_func
#define hb_draw_funcs_set_cubic_to_func           hr_draw_funcs_set_cubic_to_func
#define hb_draw_funcs_set_line_to_func            hr_draw_funcs_set_line_to_func
#define hb_draw_funcs_set_move_to_func            hr_draw_funcs_set_move_to_func
#define hb_draw_funcs_set_quadratic_to_func       hr_draw_funcs_set_quadratic_to_func
#define hb_draw_funcs_set_user_data               hr_draw_funcs_set_user_data
#define hb_draw_funcs_t                           hr_draw_funcs_t
#define hb_draw_line_to                           hr_draw_line_to
#define hb_draw_line_to_func_t                    hr_draw_line_to_func_t
#define hb_draw_move_to                           hr_draw_move_to
#define hb_draw_move_to_func_t                    hr_draw_move_to_func_t
#define hb_draw_quadratic_to                      hr_draw_quadratic_to
#define hb_draw_quadratic_to_func_t               hr_draw_quadratic_to_func_t
#define hb_draw_state_t                           hr_draw_state_t
#define hb_font_draw_glyph                        hr_font_draw_glyph
#define hb_font_draw_glyph_func_t                 hr_font_draw_glyph_func_t
#define hb_font_draw_glyph_or_fail                hr_font_draw_glyph_or_fail
#define hb_font_draw_glyph_or_fail_func_t         hr_font_draw_glyph_or_fail_func_t
#define hb_font_funcs_set_draw_glyph_func         hr_font_funcs_set_draw_glyph_func
#define hb_font_funcs_set_draw_glyph_or_fail_func hr_font_funcs_set_draw_glyph_or_fail_func
#define hb_font_funcs_t                           hr_font_funcs_t
#define hb_font_t                                 hr_font_t
#define hb_user_data_key_t                        hr_user_data_key_t

/* Constants and macros */

#define HB_DRAW_STATE_DEFAULT HR_DRAW_STATE_DEFAULT

#endif /* HARFRUST_HB_DRAW_H */
