/* Generated by scripts/gen-hb-compat-header.py. Do not edit by hand. */
#ifndef HARFRUST_HB_PAINT_H
#define HARFRUST_HB_PAINT_H
#include "hr-hb.h"
#include "hr-paint.h"
#include "hr-hb-draw.h"

/* Types, functions and callbacks */

#define hb_blob_t                                    hr_blob_t
#define hb_bool_t                                    hr_bool_t
#define hb_codepoint_t                               hr_codepoint_t
#define hb_color_line_get_color_stops                hr_color_line_get_color_stops
#define hb_color_line_get_color_stops_func_t         hr_color_line_get_color_stops_func_t
#define hb_color_line_get_extend                     hr_color_line_get_extend
#define hb_color_line_get_extend_func_t              hr_color_line_get_extend_func_t
#define hb_color_line_t                              hr_color_line_t
#define hb_color_stop_t                              hr_color_stop_t
#define hb_color_t                                   hr_color_t
#define hb_destroy_func_t                            hr_destroy_func_t
#define hb_draw_funcs_t                              hr_draw_funcs_t
#define hb_font_funcs_set_paint_glyph_func           hr_font_funcs_set_paint_glyph_func
#define hb_font_funcs_set_paint_glyph_or_fail_func   hr_font_funcs_set_paint_glyph_or_fail_func
#define hb_font_funcs_t                              hr_font_funcs_t
#define hb_font_paint_glyph                          hr_font_paint_glyph
#define hb_font_paint_glyph_func_t                   hr_font_paint_glyph_func_t
#define hb_font_paint_glyph_or_fail                  hr_font_paint_glyph_or_fail
#define hb_font_paint_glyph_or_fail_func_t           hr_font_paint_glyph_or_fail_func_t
#define hb_font_t                                    hr_font_t
#define hb_glyph_extents_t                           hr_glyph_extents_t
#define hb_paint_color                               hr_paint_color
#define hb_paint_color_func_t                        hr_paint_color_func_t
#define hb_paint_color_glyph                         hr_paint_color_glyph
#define hb_paint_color_glyph_func_t                  hr_paint_color_glyph_func_t
#define hb_paint_composite_mode_t                    hr_paint_composite_mode_t
#define hb_paint_custom_palette_color                hr_paint_custom_palette_color
#define hb_paint_custom_palette_color_func_t         hr_paint_custom_palette_color_func_t
#define hb_paint_extend_t                            hr_paint_extend_t
#define hb_paint_fill_glyph                          hr_paint_fill_glyph
#define hb_paint_fill_glyph_func_t                   hr_paint_fill_glyph_func_t
#define hb_paint_funcs_create                        hr_paint_funcs_create
#define hb_paint_funcs_destroy                       hr_paint_funcs_destroy
#define hb_paint_funcs_get_empty                     hr_paint_funcs_get_empty
#define hb_paint_funcs_get_user_data                 hr_paint_funcs_get_user_data
#define hb_paint_funcs_is_immutable                  hr_paint_funcs_is_immutable
#define hb_paint_funcs_make_immutable                hr_paint_funcs_make_immutable
#define hb_paint_funcs_reference                     hr_paint_funcs_reference
#define hb_paint_funcs_set_color_func                hr_paint_funcs_set_color_func
#define hb_paint_funcs_set_color_glyph_func          hr_paint_funcs_set_color_glyph_func
#define hb_paint_funcs_set_custom_palette_color_func hr_paint_funcs_set_custom_palette_color_func
#define hb_paint_funcs_set_fill_glyph_func           hr_paint_funcs_set_fill_glyph_func
#define hb_paint_funcs_set_image_func                hr_paint_funcs_set_image_func
#define hb_paint_funcs_set_linear_gradient_func      hr_paint_funcs_set_linear_gradient_func
#define hb_paint_funcs_set_pop_clip_func             hr_paint_funcs_set_pop_clip_func
#define hb_paint_funcs_set_pop_group_func            hr_paint_funcs_set_pop_group_func
#define hb_paint_funcs_set_pop_transform_func        hr_paint_funcs_set_pop_transform_func
#define hb_paint_funcs_set_push_clip_glyph_func      hr_paint_funcs_set_push_clip_glyph_func
#define hb_paint_funcs_set_push_clip_path_end_func   hr_paint_funcs_set_push_clip_path_end_func
#define hb_paint_funcs_set_push_clip_path_start_func hr_paint_funcs_set_push_clip_path_start_func
#define hb_paint_funcs_set_push_clip_rectangle_func  hr_paint_funcs_set_push_clip_rectangle_func
#define hb_paint_funcs_set_push_group_for_func       hr_paint_funcs_set_push_group_for_func
#define hb_paint_funcs_set_push_group_func           hr_paint_funcs_set_push_group_func
#define hb_paint_funcs_set_push_transform_func       hr_paint_funcs_set_push_transform_func
#define hb_paint_funcs_set_radial_gradient_func      hr_paint_funcs_set_radial_gradient_func
#define hb_paint_funcs_set_sweep_gradient_func       hr_paint_funcs_set_sweep_gradient_func
#define hb_paint_funcs_set_user_data                 hr_paint_funcs_set_user_data
#define hb_paint_funcs_t                             hr_paint_funcs_t
#define hb_paint_image                               hr_paint_image
#define hb_paint_image_func_t                        hr_paint_image_func_t
#define hb_paint_linear_gradient                     hr_paint_linear_gradient
#define hb_paint_linear_gradient_func_t              hr_paint_linear_gradient_func_t
#define hb_paint_pop_clip                            hr_paint_pop_clip
#define hb_paint_pop_clip_func_t                     hr_paint_pop_clip_func_t
#define hb_paint_pop_group                           hr_paint_pop_group
#define hb_paint_pop_group_func_t                    hr_paint_pop_group_func_t
#define hb_paint_pop_transform                       hr_paint_pop_transform
#define hb_paint_pop_transform_func_t                hr_paint_pop_transform_func_t
#define hb_paint_push_clip_glyph                     hr_paint_push_clip_glyph
#define hb_paint_push_clip_glyph_func_t              hr_paint_push_clip_glyph_func_t
#define hb_paint_push_clip_path_end                  hr_paint_push_clip_path_end
#define hb_paint_push_clip_path_end_func_t           hr_paint_push_clip_path_end_func_t
#define hb_paint_push_clip_path_start                hr_paint_push_clip_path_start
#define hb_paint_push_clip_path_start_func_t         hr_paint_push_clip_path_start_func_t
#define hb_paint_push_clip_rectangle                 hr_paint_push_clip_rectangle
#define hb_paint_push_clip_rectangle_func_t          hr_paint_push_clip_rectangle_func_t
#define hb_paint_push_font_transform                 hr_paint_push_font_transform
#define hb_paint_push_group                          hr_paint_push_group
#define hb_paint_push_group_for                      hr_paint_push_group_for
#define hb_paint_push_group_for_func_t               hr_paint_push_group_for_func_t
#define hb_paint_push_group_func_t                   hr_paint_push_group_func_t
#define hb_paint_push_inverse_font_transform         hr_paint_push_inverse_font_transform
#define hb_paint_push_transform                      hr_paint_push_transform
#define hb_paint_push_transform_func_t               hr_paint_push_transform_func_t
#define hb_paint_radial_gradient                     hr_paint_radial_gradient
#define hb_paint_radial_gradient_func_t              hr_paint_radial_gradient_func_t
#define hb_paint_sweep_gradient                      hr_paint_sweep_gradient
#define hb_paint_sweep_gradient_func_t               hr_paint_sweep_gradient_func_t
#define hb_tag_t                                     hr_tag_t
#define hb_user_data_key_t                           hr_user_data_key_t

/* Constants and macros */

#define HB_PAINT_COMPOSITE_MODE_CLEAR          HR_PAINT_COMPOSITE_MODE_CLEAR
#define HB_PAINT_COMPOSITE_MODE_COLOR_BURN     HR_PAINT_COMPOSITE_MODE_COLOR_BURN
#define HB_PAINT_COMPOSITE_MODE_COLOR_DODGE    HR_PAINT_COMPOSITE_MODE_COLOR_DODGE
#define HB_PAINT_COMPOSITE_MODE_DARKEN         HR_PAINT_COMPOSITE_MODE_DARKEN
#define HB_PAINT_COMPOSITE_MODE_DEST           HR_PAINT_COMPOSITE_MODE_DEST
#define HB_PAINT_COMPOSITE_MODE_DEST_ATOP      HR_PAINT_COMPOSITE_MODE_DEST_ATOP
#define HB_PAINT_COMPOSITE_MODE_DEST_IN        HR_PAINT_COMPOSITE_MODE_DEST_IN
#define HB_PAINT_COMPOSITE_MODE_DEST_OUT       HR_PAINT_COMPOSITE_MODE_DEST_OUT
#define HB_PAINT_COMPOSITE_MODE_DEST_OVER      HR_PAINT_COMPOSITE_MODE_DEST_OVER
#define HB_PAINT_COMPOSITE_MODE_DIFFERENCE     HR_PAINT_COMPOSITE_MODE_DIFFERENCE
#define HB_PAINT_COMPOSITE_MODE_EXCLUSION      HR_PAINT_COMPOSITE_MODE_EXCLUSION
#define HB_PAINT_COMPOSITE_MODE_HARD_LIGHT     HR_PAINT_COMPOSITE_MODE_HARD_LIGHT
#define HB_PAINT_COMPOSITE_MODE_HSL_COLOR      HR_PAINT_COMPOSITE_MODE_HSL_COLOR
#define HB_PAINT_COMPOSITE_MODE_HSL_HUE        HR_PAINT_COMPOSITE_MODE_HSL_HUE
#define HB_PAINT_COMPOSITE_MODE_HSL_LUMINOSITY HR_PAINT_COMPOSITE_MODE_HSL_LUMINOSITY
#define HB_PAINT_COMPOSITE_MODE_HSL_SATURATION HR_PAINT_COMPOSITE_MODE_HSL_SATURATION
#define HB_PAINT_COMPOSITE_MODE_LIGHTEN        HR_PAINT_COMPOSITE_MODE_LIGHTEN
#define HB_PAINT_COMPOSITE_MODE_MULTIPLY       HR_PAINT_COMPOSITE_MODE_MULTIPLY
#define HB_PAINT_COMPOSITE_MODE_OVERLAY        HR_PAINT_COMPOSITE_MODE_OVERLAY
#define HB_PAINT_COMPOSITE_MODE_PLUS           HR_PAINT_COMPOSITE_MODE_PLUS
#define HB_PAINT_COMPOSITE_MODE_SCREEN         HR_PAINT_COMPOSITE_MODE_SCREEN
#define HB_PAINT_COMPOSITE_MODE_SOFT_LIGHT     HR_PAINT_COMPOSITE_MODE_SOFT_LIGHT
#define HB_PAINT_COMPOSITE_MODE_SRC            HR_PAINT_COMPOSITE_MODE_SRC
#define HB_PAINT_COMPOSITE_MODE_SRC_ATOP       HR_PAINT_COMPOSITE_MODE_SRC_ATOP
#define HB_PAINT_COMPOSITE_MODE_SRC_IN         HR_PAINT_COMPOSITE_MODE_SRC_IN
#define HB_PAINT_COMPOSITE_MODE_SRC_OUT        HR_PAINT_COMPOSITE_MODE_SRC_OUT
#define HB_PAINT_COMPOSITE_MODE_SRC_OVER       HR_PAINT_COMPOSITE_MODE_SRC_OVER
#define HB_PAINT_COMPOSITE_MODE_XOR            HR_PAINT_COMPOSITE_MODE_XOR
#define HB_PAINT_EXTEND_PAD                    HR_PAINT_EXTEND_PAD
#define HB_PAINT_EXTEND_REFLECT                HR_PAINT_EXTEND_REFLECT
#define HB_PAINT_EXTEND_REPEAT                 HR_PAINT_EXTEND_REPEAT
#define HB_PAINT_IMAGE_FORMAT_BGRA             HR_PAINT_IMAGE_FORMAT_BGRA
#define HB_PAINT_IMAGE_FORMAT_PNG              HR_PAINT_IMAGE_FORMAT_PNG
#define HB_PAINT_IMAGE_FORMAT_SVG              HR_PAINT_IMAGE_FORMAT_SVG

#endif /* HARFRUST_HB_PAINT_H */
