/* Generated by cbindgen from harfrust_capi/src/paint.rs. */

#ifndef HARFRUST_PAINT_H
#define HARFRUST_PAINT_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "hr.h"
#include "hr-draw.h"
struct hr_color_line_t;

/**
 * A reference-counted, optionally immutable collection of paint callbacks.
 */
typedef struct hr_paint_funcs_t hr_paint_funcs_t;

/**
 * Callback for push transform; data must be safe to use on any thread.
 */
typedef void (*hr_paint_push_transform_func_t)(struct hr_paint_funcs_t *funcs,
                                               void *paint_data,
                                               float xx,
                                               float yx,
                                               float xy,
                                               float yy,
                                               float dx,
                                               float dy,
                                               void *user_data);

/**
 * Callback for pop transform; data must be safe to use on any thread.
 */
typedef void (*hr_paint_pop_transform_func_t)(struct hr_paint_funcs_t *funcs,
                                              void *paint_data,
                                              void *user_data);

/**
 * Callback for color glyph; data must be safe to use on any thread.
 */
typedef hr_bool_t (*hr_paint_color_glyph_func_t)(struct hr_paint_funcs_t *funcs,
                                                 void *paint_data,
                                                 hr_codepoint_t glyph,
                                                 hr_font_t *font,
                                                 void *user_data);

/**
 * Callback for push clip glyph; data must be safe to use on any thread.
 */
typedef void (*hr_paint_push_clip_glyph_func_t)(struct hr_paint_funcs_t *funcs,
                                                void *paint_data,
                                                hr_codepoint_t glyph,
                                                hr_font_t *font,
                                                void *user_data);

/**
 * Callback for push clip rectangle; data must be safe to use on any thread.
 */
typedef void (*hr_paint_push_clip_rectangle_func_t)(struct hr_paint_funcs_t *funcs,
                                                    void *paint_data,
                                                    float xmin,
                                                    float ymin,
                                                    float xmax,
                                                    float ymax,
                                                    void *user_data);

/**
 * Callback for push clip path start; data must be safe to use on any thread.
 */
typedef hr_draw_funcs_t *(*hr_paint_push_clip_path_start_func_t)(struct hr_paint_funcs_t *funcs,
                                                                 void *paint_data,
                                                                 void **draw_data,
                                                                 void *user_data);

/**
 * Callback for push clip path end; data must be safe to use on any thread.
 */
typedef void (*hr_paint_push_clip_path_end_func_t)(struct hr_paint_funcs_t *funcs,
                                                   void *paint_data,
                                                   void *user_data);

/**
 * Callback for pop clip; data must be safe to use on any thread.
 */
typedef void (*hr_paint_pop_clip_func_t)(struct hr_paint_funcs_t *funcs,
                                         void *paint_data,
                                         void *user_data);

/**
 * Callback for color; data must be safe to use on any thread.
 */
typedef void (*hr_paint_color_func_t)(struct hr_paint_funcs_t *funcs,
                                      void *paint_data,
                                      hr_bool_t is_foreground,
                                      hr_color_t color,
                                      void *user_data);

/**
 * Callback for fill glyph; data must be safe to use on any thread.
 */
typedef void (*hr_paint_fill_glyph_func_t)(struct hr_paint_funcs_t *funcs,
                                           void *paint_data,
                                           hr_codepoint_t glyph,
                                           hr_font_t *font,
                                           hr_bool_t is_foreground,
                                           hr_color_t color,
                                           void *user_data);

/**
 * Callback for image; data must be safe to use on any thread.
 */
typedef hr_bool_t (*hr_paint_image_func_t)(struct hr_paint_funcs_t *funcs,
                                           void *paint_data,
                                           hr_blob_t *image,
                                           unsigned int width,
                                           unsigned int height,
                                           hr_tag_t format,
                                           float slant,
                                           hr_glyph_extents_t *extents,
                                           void *user_data);

/**
 * One gradient stop.
 */
typedef struct hr_color_stop_t {
  float offset;
  hr_bool_t is_foreground;
  hr_color_t color;
} hr_color_stop_t;

typedef unsigned int (*hr_color_line_get_color_stops_func_t)(struct hr_color_line_t *line,
                                                             void *data,
                                                             unsigned int start,
                                                             unsigned int *count,
                                                             struct hr_color_stop_t *stops,
                                                             void *user_data);

/**
 * Gradient extend mode.
 */
typedef unsigned int hr_paint_extend_t;

typedef hr_paint_extend_t (*hr_color_line_get_extend_func_t)(struct hr_color_line_t *line,
                                                             void *data,
                                                             void *user_data);

/**
 * Borrowed gradient information, valid only for the enclosing paint callback.
 */
typedef struct hr_color_line_t {
  void *data;
  hr_color_line_get_color_stops_func_t get_color_stops;
  void *get_color_stops_user_data;
  hr_color_line_get_extend_func_t get_extend;
  void *get_extend_user_data;
  void *reserved[8];
} hr_color_line_t;

/**
 * Callback for linear gradient; data must be safe to use on any thread.
 */
typedef void (*hr_paint_linear_gradient_func_t)(struct hr_paint_funcs_t *funcs,
                                                void *paint_data,
                                                struct hr_color_line_t *color_line,
                                                float x0,
                                                float y0,
                                                float x1,
                                                float y1,
                                                float x2,
                                                float y2,
                                                void *user_data);

/**
 * Callback for radial gradient; data must be safe to use on any thread.
 */
typedef void (*hr_paint_radial_gradient_func_t)(struct hr_paint_funcs_t *funcs,
                                                void *paint_data,
                                                struct hr_color_line_t *color_line,
                                                float x0,
                                                float y0,
                                                float r0,
                                                float x1,
                                                float y1,
                                                float r1,
                                                void *user_data);

/**
 * Callback for sweep gradient; data must be safe to use on any thread.
 */
typedef void (*hr_paint_sweep_gradient_func_t)(struct hr_paint_funcs_t *funcs,
                                               void *paint_data,
                                               struct hr_color_line_t *color_line,
                                               float x0,
                                               float y0,
                                               float start_angle,
                                               float end_angle,
                                               void *user_data);

/**
 * Callback for push group; data must be safe to use on any thread.
 */
typedef void (*hr_paint_push_group_func_t)(struct hr_paint_funcs_t *funcs,
                                           void *paint_data,
                                           void *user_data);

/**
 * COLR compositing mode, with the OpenType/HarfBuzz numeric values.
 */
typedef unsigned int hr_paint_composite_mode_t;

/**
 * Callback for push group for; data must be safe to use on any thread.
 */
typedef void (*hr_paint_push_group_for_func_t)(struct hr_paint_funcs_t *funcs,
                                               void *paint_data,
                                               hr_paint_composite_mode_t mode,
                                               void *user_data);

/**
 * Callback for pop group; data must be safe to use on any thread.
 */
typedef void (*hr_paint_pop_group_func_t)(struct hr_paint_funcs_t *funcs,
                                          void *paint_data,
                                          hr_paint_composite_mode_t mode,
                                          void *user_data);

/**
 * Callback for custom palette color; data must be safe to use on any thread.
 */
typedef hr_bool_t (*hr_paint_custom_palette_color_func_t)(struct hr_paint_funcs_t *funcs,
                                                          void *paint_data,
                                                          unsigned int color_index,
                                                          hr_color_t *color,
                                                          void *user_data);

/**
 * Legacy color-glyph callback, assumed to succeed.
 */
typedef void (*hr_font_paint_glyph_func_t)(hr_font_t *font,
                                           void *font_data,
                                           hr_codepoint_t glyph,
                                           struct hr_paint_funcs_t *funcs,
                                           void *paint_data,
                                           unsigned int palette,
                                           hr_color_t foreground,
                                           void *user_data);

/**
 * Custom color-glyph callback. Returns true if painting succeeded.
 */
typedef hr_bool_t (*hr_font_paint_glyph_or_fail_func_t)(hr_font_t *font,
                                                        void *font_data,
                                                        hr_codepoint_t glyph,
                                                        struct hr_paint_funcs_t *funcs,
                                                        void *paint_data,
                                                        unsigned int palette,
                                                        hr_color_t foreground,
                                                        void *user_data);

/**
 * PNG image bytes, decoded by the client.
 */
#define HR_PAINT_IMAGE_FORMAT_PNG 1886283552

/**
 * SVG document bytes, rendered by the client.
 */
#define HR_PAINT_IMAGE_FORMAT_SVG 1937139488

/**
 * Premultiplied BGRA pixels in the sRGBA color space.
 */
#define HR_PAINT_IMAGE_FORMAT_BGRA 1111970369

#define HR_PAINT_EXTEND_PAD 0

#define HR_PAINT_EXTEND_REPEAT 1

#define HR_PAINT_EXTEND_REFLECT 2

#define HR_PAINT_COMPOSITE_MODE_CLEAR 0

#define HR_PAINT_COMPOSITE_MODE_SRC 1

#define HR_PAINT_COMPOSITE_MODE_DEST 2

#define HR_PAINT_COMPOSITE_MODE_SRC_OVER 3

#define HR_PAINT_COMPOSITE_MODE_DEST_OVER 4

#define HR_PAINT_COMPOSITE_MODE_SRC_IN 5

#define HR_PAINT_COMPOSITE_MODE_DEST_IN 6

#define HR_PAINT_COMPOSITE_MODE_SRC_OUT 7

#define HR_PAINT_COMPOSITE_MODE_DEST_OUT 8

#define HR_PAINT_COMPOSITE_MODE_SRC_ATOP 9

#define HR_PAINT_COMPOSITE_MODE_DEST_ATOP 10

#define HR_PAINT_COMPOSITE_MODE_XOR 11

#define HR_PAINT_COMPOSITE_MODE_PLUS 12

#define HR_PAINT_COMPOSITE_MODE_SCREEN 13

#define HR_PAINT_COMPOSITE_MODE_OVERLAY 14

#define HR_PAINT_COMPOSITE_MODE_DARKEN 15

#define HR_PAINT_COMPOSITE_MODE_LIGHTEN 16

#define HR_PAINT_COMPOSITE_MODE_COLOR_DODGE 17

#define HR_PAINT_COMPOSITE_MODE_COLOR_BURN 18

#define HR_PAINT_COMPOSITE_MODE_HARD_LIGHT 19

#define HR_PAINT_COMPOSITE_MODE_SOFT_LIGHT 20

#define HR_PAINT_COMPOSITE_MODE_DIFFERENCE 21

#define HR_PAINT_COMPOSITE_MODE_EXCLUSION 22

#define HR_PAINT_COMPOSITE_MODE_MULTIPLY 23

#define HR_PAINT_COMPOSITE_MODE_HSL_HUE 24

#define HR_PAINT_COMPOSITE_MODE_HSL_SATURATION 25

#define HR_PAINT_COMPOSITE_MODE_HSL_COLOR 26

#define HR_PAINT_COMPOSITE_MODE_HSL_LUMINOSITY 27

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates an owned callback collection.
 */
struct hr_paint_funcs_t *hr_paint_funcs_create(void);

/**
 * Returns the immortal empty collection.
 */
struct hr_paint_funcs_t *hr_paint_funcs_get_empty(void);

/**
 * Takes a reference. Accepts NULL.
 */
struct hr_paint_funcs_t *hr_paint_funcs_reference(struct hr_paint_funcs_t *funcs);

/**
 * Releases an owned reference and its callback data. Accepts NULL.
 */
void hr_paint_funcs_destroy(struct hr_paint_funcs_t *funcs);

/**
 * Rejects subsequent callback changes.
 */
void hr_paint_funcs_make_immutable(struct hr_paint_funcs_t *funcs);

/**
 * Reports whether callback changes are forbidden.
 */
hr_bool_t hr_paint_funcs_is_immutable(const struct hr_paint_funcs_t *funcs);

/**
 * Attaches address-keyed metadata, taking ownership only on success.
 */
hr_bool_t hr_paint_funcs_set_user_data(struct hr_paint_funcs_t *funcs,
                                       const hr_user_data_key_t *key,
                                       void *data,
                                       hr_destroy_func_t destroy,
                                       hr_bool_t replace);

/**
 * Returns borrowed metadata.
 */
void *hr_paint_funcs_get_user_data(const struct hr_paint_funcs_t *funcs,
                                   const hr_user_data_key_t *key);

/**
 * Registers push transform. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_paint_funcs_set_push_transform_func(struct hr_paint_funcs_t *funcs,
                                            hr_paint_push_transform_func_t func,
                                            void *user_data,
                                            hr_destroy_func_t destroy);

/**
 * Dispatches push transform; omitted callbacks use the HarfBuzz default.
 */
void hr_paint_push_transform(struct hr_paint_funcs_t *funcs,
                             void *paint_data,
                             float xx,
                             float yx,
                             float xy,
                             float yy,
                             float dx,
                             float dy);

/**
 * Registers pop transform. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_paint_funcs_set_pop_transform_func(struct hr_paint_funcs_t *funcs,
                                           hr_paint_pop_transform_func_t func,
                                           void *user_data,
                                           hr_destroy_func_t destroy);

/**
 * Dispatches pop transform; omitted callbacks use the HarfBuzz default.
 */
void hr_paint_pop_transform(struct hr_paint_funcs_t *funcs, void *paint_data);

/**
 * Registers color glyph. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_paint_funcs_set_color_glyph_func(struct hr_paint_funcs_t *funcs,
                                         hr_paint_color_glyph_func_t func,
                                         void *user_data,
                                         hr_destroy_func_t destroy);

/**
 * Dispatches color glyph; omitted callbacks use the HarfBuzz default.
 */
hr_bool_t hr_paint_color_glyph(struct hr_paint_funcs_t *funcs,
                               void *paint_data,
                               hr_codepoint_t glyph,
                               hr_font_t *font);

/**
 * Registers push clip glyph. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_paint_funcs_set_push_clip_glyph_func(struct hr_paint_funcs_t *funcs,
                                             hr_paint_push_clip_glyph_func_t func,
                                             void *user_data,
                                             hr_destroy_func_t destroy);

/**
 * Dispatches push clip glyph; omitted callbacks use the HarfBuzz default.
 */
void hr_paint_push_clip_glyph(struct hr_paint_funcs_t *funcs,
                              void *paint_data,
                              hr_codepoint_t glyph,
                              hr_font_t *font);

/**
 * Registers push clip rectangle. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_paint_funcs_set_push_clip_rectangle_func(struct hr_paint_funcs_t *funcs,
                                                 hr_paint_push_clip_rectangle_func_t func,
                                                 void *user_data,
                                                 hr_destroy_func_t destroy);

/**
 * Dispatches push clip rectangle; omitted callbacks use the HarfBuzz default.
 */
void hr_paint_push_clip_rectangle(struct hr_paint_funcs_t *funcs,
                                  void *paint_data,
                                  float xmin,
                                  float ymin,
                                  float xmax,
                                  float ymax);

/**
 * Registers push clip path start. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_paint_funcs_set_push_clip_path_start_func(struct hr_paint_funcs_t *funcs,
                                                  hr_paint_push_clip_path_start_func_t func,
                                                  void *user_data,
                                                  hr_destroy_func_t destroy);

/**
 * Dispatches push clip path start; omitted callbacks use the HarfBuzz default.
 */
hr_draw_funcs_t *hr_paint_push_clip_path_start(struct hr_paint_funcs_t *funcs,
                                               void *paint_data,
                                               void **draw_data);

/**
 * Registers push clip path end. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_paint_funcs_set_push_clip_path_end_func(struct hr_paint_funcs_t *funcs,
                                                hr_paint_push_clip_path_end_func_t func,
                                                void *user_data,
                                                hr_destroy_func_t destroy);

/**
 * Dispatches push clip path end; omitted callbacks use the HarfBuzz default.
 */
void hr_paint_push_clip_path_end(struct hr_paint_funcs_t *funcs, void *paint_data);

/**
 * Registers pop clip. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_paint_funcs_set_pop_clip_func(struct hr_paint_funcs_t *funcs,
                                      hr_paint_pop_clip_func_t func,
                                      void *user_data,
                                      hr_destroy_func_t destroy);

/**
 * Dispatches pop clip; omitted callbacks use the HarfBuzz default.
 */
void hr_paint_pop_clip(struct hr_paint_funcs_t *funcs, void *paint_data);

/**
 * Registers color. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_paint_funcs_set_color_func(struct hr_paint_funcs_t *funcs,
                                   hr_paint_color_func_t func,
                                   void *user_data,
                                   hr_destroy_func_t destroy);

/**
 * Dispatches color; omitted callbacks use the HarfBuzz default.
 */
void hr_paint_color(struct hr_paint_funcs_t *funcs,
                    void *paint_data,
                    hr_bool_t is_foreground,
                    hr_color_t color);

/**
 * Registers fill glyph. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_paint_funcs_set_fill_glyph_func(struct hr_paint_funcs_t *funcs,
                                        hr_paint_fill_glyph_func_t func,
                                        void *user_data,
                                        hr_destroy_func_t destroy);

/**
 * Dispatches fill glyph; omitted callbacks use the HarfBuzz default.
 */
void hr_paint_fill_glyph(struct hr_paint_funcs_t *funcs,
                         void *paint_data,
                         hr_codepoint_t glyph,
                         hr_font_t *font,
                         hr_bool_t is_foreground,
                         hr_color_t color);

/**
 * Registers image. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_paint_funcs_set_image_func(struct hr_paint_funcs_t *funcs,
                                   hr_paint_image_func_t func,
                                   void *user_data,
                                   hr_destroy_func_t destroy);

/**
 * Dispatches image; omitted callbacks use the HarfBuzz default.
 */
hr_bool_t hr_paint_image(struct hr_paint_funcs_t *funcs,
                         void *paint_data,
                         hr_blob_t *image,
                         unsigned int width,
                         unsigned int height,
                         hr_tag_t format,
                         float slant,
                         hr_glyph_extents_t *extents);

/**
 * Registers linear gradient. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_paint_funcs_set_linear_gradient_func(struct hr_paint_funcs_t *funcs,
                                             hr_paint_linear_gradient_func_t func,
                                             void *user_data,
                                             hr_destroy_func_t destroy);

/**
 * Dispatches linear gradient; omitted callbacks use the HarfBuzz default.
 */
void hr_paint_linear_gradient(struct hr_paint_funcs_t *funcs,
                              void *paint_data,
                              struct hr_color_line_t *color_line,
                              float x0,
                              float y0,
                              float x1,
                              float y1,
                              float x2,
                              float y2);

/**
 * Registers radial gradient. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_paint_funcs_set_radial_gradient_func(struct hr_paint_funcs_t *funcs,
                                             hr_paint_radial_gradient_func_t func,
                                             void *user_data,
                                             hr_destroy_func_t destroy);

/**
 * Dispatches radial gradient; omitted callbacks use the HarfBuzz default.
 */
void hr_paint_radial_gradient(struct hr_paint_funcs_t *funcs,
                              void *paint_data,
                              struct hr_color_line_t *color_line,
                              float x0,
                              float y0,
                              float r0,
                              float x1,
                              float y1,
                              float r1);

/**
 * Registers sweep gradient. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_paint_funcs_set_sweep_gradient_func(struct hr_paint_funcs_t *funcs,
                                            hr_paint_sweep_gradient_func_t func,
                                            void *user_data,
                                            hr_destroy_func_t destroy);

/**
 * Dispatches sweep gradient; omitted callbacks use the HarfBuzz default.
 */
void hr_paint_sweep_gradient(struct hr_paint_funcs_t *funcs,
                             void *paint_data,
                             struct hr_color_line_t *color_line,
                             float x0,
                             float y0,
                             float start_angle,
                             float end_angle);

/**
 * Registers push group. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_paint_funcs_set_push_group_func(struct hr_paint_funcs_t *funcs,
                                        hr_paint_push_group_func_t func,
                                        void *user_data,
                                        hr_destroy_func_t destroy);

/**
 * Dispatches push group; omitted callbacks use the HarfBuzz default.
 */
void hr_paint_push_group(struct hr_paint_funcs_t *funcs, void *paint_data);

/**
 * Registers push group for. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_paint_funcs_set_push_group_for_func(struct hr_paint_funcs_t *funcs,
                                            hr_paint_push_group_for_func_t func,
                                            void *user_data,
                                            hr_destroy_func_t destroy);

/**
 * Dispatches push group for; omitted callbacks use the HarfBuzz default.
 */
void hr_paint_push_group_for(struct hr_paint_funcs_t *funcs,
                             void *paint_data,
                             hr_paint_composite_mode_t mode);

/**
 * Registers pop group. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_paint_funcs_set_pop_group_func(struct hr_paint_funcs_t *funcs,
                                       hr_paint_pop_group_func_t func,
                                       void *user_data,
                                       hr_destroy_func_t destroy);

/**
 * Dispatches pop group; omitted callbacks use the HarfBuzz default.
 */
void hr_paint_pop_group(struct hr_paint_funcs_t *funcs,
                        void *paint_data,
                        hr_paint_composite_mode_t mode);

/**
 * Registers custom palette color. Takes ownership of data, including when clearing or rejected.
 * Mutation requires exclusive access; funcs must be NULL or live.
 */
void hr_paint_funcs_set_custom_palette_color_func(struct hr_paint_funcs_t *funcs,
                                                  hr_paint_custom_palette_color_func_t func,
                                                  void *user_data,
                                                  hr_destroy_func_t destroy);

/**
 * Dispatches custom palette color; omitted callbacks use the HarfBuzz default.
 */
hr_bool_t hr_paint_custom_palette_color(struct hr_paint_funcs_t *funcs,
                                        void *paint_data,
                                        unsigned int color_index,
                                        hr_color_t *color);

/**
 * Returns the total number of stops and copies a paginated slice if requested.
 */
unsigned int hr_color_line_get_color_stops(struct hr_color_line_t *line,
                                           unsigned int start,
                                           unsigned int *count,
                                           struct hr_color_stop_t *stops);

/**
 * Returns the extend mode, or PAD when absent.
 */
hr_paint_extend_t hr_color_line_get_extend(struct hr_color_line_t *line);

/**
 * Applies the font's scale relative to design units.
 */
void hr_paint_push_font_transform(struct hr_paint_funcs_t *funcs, void *data, hr_font_t *font);

/**
 * Applies the inverse font scale; zero axes stay zero.
 */
void hr_paint_push_inverse_font_transform(struct hr_paint_funcs_t *funcs,
                                          void *data,
                                          hr_font_t *font);

/**
 * Registers custom painting, owning its data even on rejection or clearing.
 */
void hr_font_funcs_set_paint_glyph_func(hr_font_funcs_t *ffuncs,
                                        hr_font_paint_glyph_func_t func,
                                        void *user_data,
                                        hr_destroy_func_t destroy);

/**
 * Registers custom painting returning success.
 */
void hr_font_funcs_set_paint_glyph_or_fail_func(hr_font_funcs_t *ffuncs,
                                                hr_font_paint_glyph_or_fail_func_t func,
                                                void *user_data,
                                                hr_destroy_func_t destroy);

/**
 * Paints COLRv0/v1, SVG, CBDT or sbix through client callbacks.
 * Returns false on malformed data, unsupported images, or paint failure.
 * Pointers must be NULL or live; callbacks must not mutate the font or funcs.
 */
hr_bool_t hr_font_paint_glyph_or_fail(hr_font_t *font,
                                      hr_codepoint_t glyph,
                                      struct hr_paint_funcs_t *funcs,
                                      void *data,
                                      unsigned int palette,
                                      hr_color_t foreground);

/**
 * Compatibility entry point ignoring the success result.
 */
void hr_font_paint_glyph(hr_font_t *font,
                         hr_codepoint_t glyph,
                         struct hr_paint_funcs_t *funcs,
                         void *data,
                         unsigned int palette,
                         hr_color_t foreground);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* HARFRUST_PAINT_H */
