/* Generated by cbindgen from the harfrust-capi crate. Do not edit by hand.
 *
 * Regenerate with:
 *
 *   cbindgen --config harfrust-capi/cbindgen.toml \
 *            --crate harfrust-capi \
 *            --output harfrust-capi/include/hr.h
 *
 * This is the C API for HarfRust, mirroring the shaping half of HarfBuzz's
 * API with an `hr_` prefix in place of `hb_`. Enumerators, flag values and
 * struct layouts match their HarfBuzz counterparts exactly.
 */


#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

/**
 * Value applied to a feature that covers the whole buffer, as its start.
 */
#define HR_FEATURE_GLOBAL_START 0

/**
 * Value applied to a feature that covers the whole buffer, as its end.
 *
 * Spelled as a literal rather than `c_uint::MAX` so that it reaches the
 * generated header.
 */
#define HR_FEATURE_GLOBAL_END 4294967295

/**
 * The major version of this library.
 *
 * These are literals so that they reach the generated header, and a test
 * keeps them in step with the crate version.
 */
#define HR_VERSION_MAJOR 0

/**
 * The minor version of this library.
 */
#define HR_VERSION_MINOR 13

/**
 * The micro version of this library.
 */
#define HR_VERSION_MICRO 3

/**
 * How clusters are merged during shaping.
 */
typedef enum hr_buffer_cluster_level_t {
  /**
   * Merge clusters by grapheme, keeping cluster values monotonic.
   */
  HR_BUFFER_CLUSTER_LEVEL_MONOTONE_GRAPHEMES = 0,
  /**
   * Merge clusters by character, keeping cluster values monotonic.
   */
  HR_BUFFER_CLUSTER_LEVEL_MONOTONE_CHARACTERS = 1,
  /**
   * Do not merge clusters, and do not keep cluster values monotonic.
   */
  HR_BUFFER_CLUSTER_LEVEL_CHARACTERS = 2,
  /**
   * Merge clusters by grapheme without keeping cluster values monotonic.
   */
  HR_BUFFER_CLUSTER_LEVEL_GRAPHEMES = 3,
} hr_buffer_cluster_level_t;

/**
 * What a buffer currently holds.
 */
typedef enum hr_buffer_content_type_t {
  /**
   * Nothing, or contents that have been cleared.
   */
  HR_BUFFER_CONTENT_TYPE_INVALID = 0,
  /**
   * Input characters, ready to be shaped.
   */
  HR_BUFFER_CONTENT_TYPE_UNICODE = 1,
  /**
   * The glyphs shaping produced.
   */
  HR_BUFFER_CONTENT_TYPE_GLYPHS = 2,
} hr_buffer_content_type_t;

/**
 * The format `hr_buffer_serialize_glyphs` writes.
 */
typedef enum hr_buffer_serialize_format_t {
  /**
   * A human-readable one-line form.
   */
  HR_BUFFER_SERIALIZE_FORMAT_TEXT = 1413830740,
  /**
   * JSON. Not supported by this library.
   */
  HR_BUFFER_SERIALIZE_FORMAT_JSON = 1246973774,
  /**
   * An unrecognised format.
   */
  HR_BUFFER_SERIALIZE_FORMAT_INVALID = 0,
} hr_buffer_serialize_format_t;

/**
 * How a blob relates to the memory it was created over.
 */
typedef enum hr_memory_mode_t {
  /**
   * Copy the data. The caller keeps ownership of the original buffer.
   */
  HR_MEMORY_MODE_DUPLICATE = 0,
  /**
   * Use the data in place. It must outlive the blob and never change.
   */
  HR_MEMORY_MODE_READONLY = 1,
  /**
   * Use the data in place. Treated as read-only by this library.
   */
  HR_MEMORY_MODE_WRITABLE = 2,
  /**
   * Use the data in place. Treated as read-only by this library.
   */
  HR_MEMORY_MODE_READONLY_MAY_MAKE_WRITABLE = 3,
} hr_memory_mode_t;

/**
 * Binary data with a lifetime.
 */
typedef struct hr_blob_t hr_blob_t;

/**
 * A buffer of text to shape, and of the glyphs shaping produces.
 */
typedef struct hr_buffer_t hr_buffer_t;

/**
 * A font face: the tables of one font, before any size or variation settings.
 */
typedef struct hr_face_t hr_face_t;

/**
 * A set of font callbacks.
 */
typedef struct hr_font_funcs_t hr_font_funcs_t;

/**
 * A font: a face with a scale, an optional point size, and variation
 * settings applied.
 */
typedef struct hr_font_t hr_font_t;

/**
 * An interned language tag.
 *
 * Language values are interned for the lifetime of the process, so they may
 * be compared by pointer and never need to be freed.
 */
typedef struct hr_language_impl_t hr_language_impl_t;

/**
 * A reusable plan for shaping text with given properties.
 */
typedef struct hr_shape_plan_t hr_shape_plan_t;

/**
 * Callback invoked to release a `user_data` value.
 */
typedef void (*hr_destroy_func_t)(void *user_data);

/**
 * A boolean, as C sees it: zero is false, non-zero is true.
 */
typedef int hr_bool_t;

/**
 * Key used to attach and retrieve user data on an object.
 *
 * Only the address of the key matters; its contents are never read.
 */
typedef struct hr_user_data_key_t {
  /**
   * Unused; present so the struct has a well-defined size in C.
   */
  char unused;
} hr_user_data_key_t;

/**
 * A Unicode scalar value.
 */
typedef uint32_t hr_codepoint_t;

/**
 * The direction in which text is set.
 *
 * This is an integer typedef rather than an enumeration because it appears in
 * [`hr_segment_properties_t`], which callers fill in themselves; a value
 * outside the set below is then merely unrecognised rather than undefined.
 */
typedef uint32_t hr_direction_t;

/**
 * A four byte OpenType tag, packed big-endian into a 32 bit integer.
 */
typedef uint32_t hr_tag_t;

/**
 * An ISO 15924 script, held as its four byte tag.
 *
 * HarfBuzz declares `hb_script_t` as an enum; here it is a tag typedef so
 * that arbitrary scripts round-trip without a cast. The `HR_SCRIPT_*`
 * constants below carry the same values as HarfBuzz's enumerators.
 */
typedef hr_tag_t hr_script_t;

/**
 * A language, as an interned pointer. `NULL` means "unset".
 */
typedef const struct hr_language_impl_t *hr_language_t;

/**
 * Flags controlling how a buffer is shaped.
 *
 * These are combined with a bitwise or, so this is an integer typedef rather
 * than an enumeration.
 */
typedef uint32_t hr_buffer_flags_t;

/**
 * A mask of feature bits applied to an item in a buffer.
 */
typedef uint32_t hr_mask_t;

/**
 * One item in a buffer: an input character before shaping, a glyph after.
 */
typedef struct hr_glyph_info_t {
  /**
   * The input codepoint before shaping, the glyph index after.
   */
  hr_codepoint_t codepoint;
  /**
   * Reserved for internal use.
   */
  hr_mask_t mask;
  /**
   * Index into the input text of the cluster this item belongs to.
   */
  uint32_t cluster;
  /**
   * Reserved for internal use.
   */
  uint32_t var1;
  /**
   * Reserved for internal use.
   */
  uint32_t var2;
} hr_glyph_info_t;

/**
 * A position, in whatever units the configured font scale implies.
 */
typedef int32_t hr_position_t;

/**
 * The position of one glyph, relative to the current point.
 */
typedef struct hr_glyph_position_t {
  /**
   * How far the pen moves after this glyph, when setting horizontally.
   */
  hr_position_t x_advance;
  /**
   * How far the pen moves after this glyph, when setting vertically.
   */
  hr_position_t y_advance;
  /**
   * How far this glyph shifts on the x-axis before being drawn.
   */
  hr_position_t x_offset;
  /**
   * How far this glyph shifts on the y-axis before being drawn.
   */
  hr_position_t y_offset;
  /**
   * Reserved for internal use.
   */
  uint32_t var;
} hr_glyph_position_t;

/**
 * Flags attached to an individual glyph by shaping.
 *
 * These are combined with a bitwise or, so this is an integer typedef rather
 * than an enumeration.
 */
typedef uint32_t hr_glyph_flags_t;

/**
 * The direction, script and language a run of text is set in.
 *
 * Zeroing this struct leaves every field unset, which is what
 * `HR_SEGMENT_PROPERTIES_DEFAULT` expands to.
 */
typedef struct hr_segment_properties_t {
  /**
   * The direction the text is set in.
   */
  hr_direction_t direction;
  /**
   * The script the text is written in.
   */
  hr_script_t script;
  /**
   * The language the text is in, or `NULL` if unset.
   */
  hr_language_t language;
  /**
   * Reserved; always set to `NULL`.
   */
  void *reserved1;
  /**
   * Reserved; always set to `NULL`.
   */
  void *reserved2;
} hr_segment_properties_t;

/**
 * Flags controlling what `hr_buffer_serialize_glyphs` includes.
 *
 * These are combined with a bitwise or, so this is an integer typedef rather
 * than an enumeration.
 */
typedef uint32_t hr_buffer_serialize_flags_t;

/**
 * A feature tag with the value to apply and the range to apply it over.
 */
typedef struct hr_feature_t {
  /**
   * The feature's OpenType tag.
   */
  hr_tag_t tag;
  /**
   * The value to apply. Zero disables the feature; one enables it.
   */
  uint32_t value;
  /**
   * Index of the first item the feature applies to.
   */
  unsigned int start;
  /**
   * Index one past the last item the feature applies to.
   */
  unsigned int end;
} hr_feature_t;

/**
 * A variation axis tag and the value to set it to, in user space.
 */
typedef struct hr_variation_t {
  /**
   * The axis's OpenType tag.
   */
  hr_tag_t tag;
  /**
   * The value to set the axis to, in user space.
   */
  float value;
} hr_variation_t;

/**
 * Callback returning the data for one table of a face.
 *
 * The callback owns the reference it returns; this library takes it over and
 * releases it. Return `NULL` for a table the face does not have.
 */
typedef struct hr_blob_t *(*hr_reference_table_func_t)(struct hr_face_t *face,
                                                       hr_tag_t tag,
                                                       void *user_data);

/**
 * Maps a Unicode scalar value to a glyph. Returns false if there is none.
 */
typedef hr_bool_t (*hr_font_get_nominal_glyph_func_t)(struct hr_font_t *font,
                                                      void *font_data,
                                                      hr_codepoint_t unicode,
                                                      hr_codepoint_t *glyph,
                                                      void *user_data);

/**
 * Maps a Unicode scalar value and variation selector to a glyph.
 */
typedef hr_bool_t (*hr_font_get_variation_glyph_func_t)(struct hr_font_t *font,
                                                        void *font_data,
                                                        hr_codepoint_t unicode,
                                                        hr_codepoint_t variation_selector,
                                                        hr_codepoint_t *glyph,
                                                        void *user_data);

/**
 * Returns a glyph's advance along the current direction.
 */
typedef hr_position_t (*hr_font_get_glyph_advance_func_t)(struct hr_font_t *font,
                                                          void *font_data,
                                                          hr_codepoint_t glyph,
                                                          void *user_data);

/**
 * Returns a glyph's origin along the current direction.
 */
typedef hr_bool_t (*hr_font_get_glyph_origin_func_t)(struct hr_font_t *font,
                                                     void *font_data,
                                                     hr_codepoint_t glyph,
                                                     hr_position_t *x,
                                                     hr_position_t *y,
                                                     void *user_data);

/**
 * The ink extents of a glyph, in the font's scaled units.
 */
typedef struct hr_glyph_extents_t {
  /**
   * Horizontal bearing from the glyph origin to the left of the ink box.
   */
  hr_position_t x_bearing;
  /**
   * Vertical bearing from the glyph origin to the top of the ink box.
   */
  hr_position_t y_bearing;
  /**
   * Width of the ink box.
   */
  hr_position_t width;
  /**
   * Height of the ink box, measured downwards.
   */
  hr_position_t height;
} hr_glyph_extents_t;

/**
 * Returns a glyph's ink extents.
 */
typedef hr_bool_t (*hr_font_get_glyph_extents_func_t)(struct hr_font_t *font,
                                                      void *font_data,
                                                      hr_codepoint_t glyph,
                                                      struct hr_glyph_extents_t *extents,
                                                      void *user_data);

/**
 * No flags set.
 */
#define HR_BUFFER_FLAG_DEFAULT 0

/**
 * The buffer holds the start of a paragraph.
 */
#define HR_BUFFER_FLAG_BOT 1

/**
 * The buffer holds the end of a paragraph.
 */
#define HR_BUFFER_FLAG_EOT 2

/**
 * Show default-ignorable characters using the font's own glyphs.
 */
#define HR_BUFFER_FLAG_PRESERVE_DEFAULT_IGNORABLES 4

/**
 * Remove default-ignorable characters entirely.
 */
#define HR_BUFFER_FLAG_REMOVE_DEFAULT_IGNORABLES 8

/**
 * Do not insert a dotted circle around invalid sequences.
 */
#define HR_BUFFER_FLAG_DO_NOT_INSERT_DOTTED_CIRCLE 16

/**
 * Verify the shaping result. Accepted but not yet acted on.
 */
#define HR_BUFFER_FLAG_VERIFY 32

/**
 * Produce the unsafe-to-concat glyph flag, which costs extra work.
 */
#define HR_BUFFER_FLAG_PRODUCE_UNSAFE_TO_CONCAT 64

/**
 * Produce the safe-to-insert-tatweel glyph flag.
 */
#define HR_BUFFER_FLAG_PRODUCE_SAFE_TO_INSERT_TATWEEL 128

/**
 * Every flag defined above.
 */
#define HR_BUFFER_FLAG_DEFINED 255

/**
 * Breaking the text at this cluster requires reshaping both sides.
 */
#define HR_GLYPH_FLAG_UNSAFE_TO_BREAK 1

/**
 * Changing the text on one side of this cluster may change the other.
 */
#define HR_GLYPH_FLAG_UNSAFE_TO_CONCAT 2

/**
 * A tatweel may be inserted before this cluster to elongate the run.
 */
#define HR_GLYPH_FLAG_SAFE_TO_INSERT_TATWEEL 4

/**
 * Every flag defined above.
 */
#define HR_GLYPH_FLAG_DEFINED 7

/**
 * Include everything.
 */
#define HR_BUFFER_SERIALIZE_FLAG_DEFAULT 0

/**
 * Leave out cluster values.
 */
#define HR_BUFFER_SERIALIZE_FLAG_NO_CLUSTERS 1

/**
 * Leave out positions.
 */
#define HR_BUFFER_SERIALIZE_FLAG_NO_POSITIONS 2

/**
 * Write glyph indices rather than names.
 */
#define HR_BUFFER_SERIALIZE_FLAG_NO_GLYPH_NAMES 4

/**
 * Include each glyph's ink extents.
 */
#define HR_BUFFER_SERIALIZE_FLAG_GLYPH_EXTENTS 8

/**
 * Include each glyph's flags.
 */
#define HR_BUFFER_SERIALIZE_FLAG_GLYPH_FLAGS 16

/**
 * Leave out advances, making offsets absolute.
 */
#define HR_BUFFER_SERIALIZE_FLAG_NO_ADVANCES 32

/**
 * Every flag defined above.
 */
#define HR_BUFFER_SERIALIZE_FLAG_DEFINED 63

/**
 * The tag matching no script, language or feature.
 */
#define HR_TAG_NONE 0

/**
 * The largest possible tag value.
 */
#define HR_TAG_MAX 4294967295

/**
 * The largest possible tag value that is still signed-safe.
 */
#define HR_TAG_MAX_SIGNED 2147483647

/**
 * Initial, unset direction.
 */
#define HR_DIRECTION_INVALID 0

/**
 * Text is set horizontally from left to right.
 */
#define HR_DIRECTION_LTR 4

/**
 * Text is set horizontally from right to left.
 */
#define HR_DIRECTION_RTL 5

/**
 * Text is set vertically from top to bottom.
 */
#define HR_DIRECTION_TTB 6

/**
 * Text is set vertically from bottom to top.
 */
#define HR_DIRECTION_BTT 7

/**
 * The script matching no script at all.
 */
#define HR_SCRIPT_INVALID HR_TAG_NONE

/**
 * The Common script (`Zyyy`).
 */
#define HR_SCRIPT_COMMON 1517910393

/**
 * The Inherited script (`Zinh`).
 */
#define HR_SCRIPT_INHERITED 1516858984

/**
 * The Arabic script (`Arab`).
 */
#define HR_SCRIPT_ARABIC 1098015074

/**
 * The Armenian script (`Armn`).
 */
#define HR_SCRIPT_ARMENIAN 1098018158

/**
 * The Bengali script (`Beng`).
 */
#define HR_SCRIPT_BENGALI 1113943655

/**
 * The Cyrillic script (`Cyrl`).
 */
#define HR_SCRIPT_CYRILLIC 1132032620

/**
 * The Devanagari script (`Deva`).
 */
#define HR_SCRIPT_DEVANAGARI 1147500129

/**
 * The Georgian script (`Geor`).
 */
#define HR_SCRIPT_GEORGIAN 1197830002

/**
 * The Greek script (`Grek`).
 */
#define HR_SCRIPT_GREEK 1198679403

/**
 * The Gujarati script (`Gujr`).
 */
#define HR_SCRIPT_GUJARATI 1198877298

/**
 * The Gurmukhi script (`Guru`).
 */
#define HR_SCRIPT_GURMUKHI 1198879349

/**
 * The Hangul script (`Hang`).
 */
#define HR_SCRIPT_HANGUL 1214344807

/**
 * The Han script (`Hani`).
 */
#define HR_SCRIPT_HAN 1214344809

/**
 * The Hebrew script (`Hebr`).
 */
#define HR_SCRIPT_HEBREW 1214603890

/**
 * The Hiragana script (`Hira`).
 */
#define HR_SCRIPT_HIRAGANA 1214870113

/**
 * The Kannada script (`Knda`).
 */
#define HR_SCRIPT_KANNADA 1265525857

/**
 * The Katakana script (`Kana`).
 */
#define HR_SCRIPT_KATAKANA 1264676449

/**
 * The Lao script (`Laoo`).
 */
#define HR_SCRIPT_LAO 1281453935

/**
 * The Latin script (`Latn`).
 */
#define HR_SCRIPT_LATIN 1281455214

/**
 * The Malayalam script (`Mlym`).
 */
#define HR_SCRIPT_MALAYALAM 1298954605

/**
 * The Oriya script (`Orya`).
 */
#define HR_SCRIPT_ORIYA 1332902241

/**
 * The Tamil script (`Taml`).
 */
#define HR_SCRIPT_TAMIL 1415671148

/**
 * The Telugu script (`Telu`).
 */
#define HR_SCRIPT_TELUGU 1415933045

/**
 * The Thai script (`Thai`).
 */
#define HR_SCRIPT_THAI 1416126825

/**
 * The Tibetan script (`Tibt`).
 */
#define HR_SCRIPT_TIBETAN 1416192628

/**
 * The Bopomofo script (`Bopo`).
 */
#define HR_SCRIPT_BOPOMOFO 1114599535

/**
 * The Braille script (`Brai`).
 */
#define HR_SCRIPT_BRAILLE 1114792297

/**
 * The Canadian Syllabics script (`Cans`).
 */
#define HR_SCRIPT_CANADIAN_SYLLABICS 1130458739

/**
 * The Cherokee script (`Cher`).
 */
#define HR_SCRIPT_CHEROKEE 1130915186

/**
 * The Ethiopic script (`Ethi`).
 */
#define HR_SCRIPT_ETHIOPIC 1165256809

/**
 * The Khmer script (`Khmr`).
 */
#define HR_SCRIPT_KHMER 1265134962

/**
 * The Mongolian script (`Mong`).
 */
#define HR_SCRIPT_MONGOLIAN 1299148391

/**
 * The Myanmar script (`Mymr`).
 */
#define HR_SCRIPT_MYANMAR 1299803506

/**
 * The Ogham script (`Ogam`).
 */
#define HR_SCRIPT_OGHAM 1332175213

/**
 * The Runic script (`Runr`).
 */
#define HR_SCRIPT_RUNIC 1383427698

/**
 * The Sinhala script (`Sinh`).
 */
#define HR_SCRIPT_SINHALA 1399418472

/**
 * The Syriac script (`Syrc`).
 */
#define HR_SCRIPT_SYRIAC 1400468067

/**
 * The Thaana script (`Thaa`).
 */
#define HR_SCRIPT_THAANA 1416126817

/**
 * The Yi script (`Yiii`).
 */
#define HR_SCRIPT_YI 1500080489

/**
 * The Deseret script (`Dsrt`).
 */
#define HR_SCRIPT_DESERET 1148416628

/**
 * The Gothic script (`Goth`).
 */
#define HR_SCRIPT_GOTHIC 1198486632

/**
 * The Old Italic script (`Ital`).
 */
#define HR_SCRIPT_OLD_ITALIC 1232363884

/**
 * The Buhid script (`Buhd`).
 */
#define HR_SCRIPT_BUHID 1114990692

/**
 * The Hanunoo script (`Hano`).
 */
#define HR_SCRIPT_HANUNOO 1214344815

/**
 * The Tagalog script (`Tglg`).
 */
#define HR_SCRIPT_TAGALOG 1416064103

/**
 * The Tagbanwa script (`Tagb`).
 */
#define HR_SCRIPT_TAGBANWA 1415669602

/**
 * The Cypriot script (`Cprt`).
 */
#define HR_SCRIPT_CYPRIOT 1131442804

/**
 * The Limbu script (`Limb`).
 */
#define HR_SCRIPT_LIMBU 1281977698

/**
 * The Linear B script (`Linb`).
 */
#define HR_SCRIPT_LINEAR_B 1281977954

/**
 * The Osmanya script (`Osma`).
 */
#define HR_SCRIPT_OSMANYA 1332964705

/**
 * The Shavian script (`Shaw`).
 */
#define HR_SCRIPT_SHAVIAN 1399349623

/**
 * The Tai Le script (`Tale`).
 */
#define HR_SCRIPT_TAI_LE 1415670885

/**
 * The Ugaritic script (`Ugar`).
 */
#define HR_SCRIPT_UGARITIC 1432838514

/**
 * The Buginese script (`Bugi`).
 */
#define HR_SCRIPT_BUGINESE 1114990441

/**
 * The Coptic script (`Copt`).
 */
#define HR_SCRIPT_COPTIC 1131376756

/**
 * The Glagolitic script (`Glag`).
 */
#define HR_SCRIPT_GLAGOLITIC 1198285159

/**
 * The Kharoshthi script (`Khar`).
 */
#define HR_SCRIPT_KHAROSHTHI 1265131890

/**
 * The New Tai Lue script (`Talu`).
 */
#define HR_SCRIPT_NEW_TAI_LUE 1415670901

/**
 * The Old Persian script (`Xpeo`).
 */
#define HR_SCRIPT_OLD_PERSIAN 1483761007

/**
 * The Syloti Nagri script (`Sylo`).
 */
#define HR_SCRIPT_SYLOTI_NAGRI 1400466543

/**
 * The Tifinagh script (`Tfng`).
 */
#define HR_SCRIPT_TIFINAGH 1415999079

/**
 * The Unknown script (`Zzzz`).
 */
#define HR_SCRIPT_UNKNOWN 1517976186

/**
 * The Balinese script (`Bali`).
 */
#define HR_SCRIPT_BALINESE 1113681001

/**
 * The Cuneiform script (`Xsux`).
 */
#define HR_SCRIPT_CUNEIFORM 1483961720

/**
 * The Nko script (`Nkoo`).
 */
#define HR_SCRIPT_NKO 1315663727

/**
 * The Phags Pa script (`Phag`).
 */
#define HR_SCRIPT_PHAGS_PA 1349017959

/**
 * The Phoenician script (`Phnx`).
 */
#define HR_SCRIPT_PHOENICIAN 1349021304

/**
 * The Carian script (`Cari`).
 */
#define HR_SCRIPT_CARIAN 1130459753

/**
 * The Cham script (`Cham`).
 */
#define HR_SCRIPT_CHAM 1130914157

/**
 * The Kayah Li script (`Kali`).
 */
#define HR_SCRIPT_KAYAH_LI 1264675945

/**
 * The Lepcha script (`Lepc`).
 */
#define HR_SCRIPT_LEPCHA 1281716323

/**
 * The Lycian script (`Lyci`).
 */
#define HR_SCRIPT_LYCIAN 1283023721

/**
 * The Lydian script (`Lydi`).
 */
#define HR_SCRIPT_LYDIAN 1283023977

/**
 * The Ol Chiki script (`Olck`).
 */
#define HR_SCRIPT_OL_CHIKI 1332503403

/**
 * The Rejang script (`Rjng`).
 */
#define HR_SCRIPT_REJANG 1382706791

/**
 * The Saurashtra script (`Saur`).
 */
#define HR_SCRIPT_SAURASHTRA 1398895986

/**
 * The Sundanese script (`Sund`).
 */
#define HR_SCRIPT_SUNDANESE 1400204900

/**
 * The Vai script (`Vaii`).
 */
#define HR_SCRIPT_VAI 1449224553

/**
 * The Avestan script (`Avst`).
 */
#define HR_SCRIPT_AVESTAN 1098281844

/**
 * The Bamum script (`Bamu`).
 */
#define HR_SCRIPT_BAMUM 1113681269

/**
 * The Egyptian Hieroglyphs script (`Egyp`).
 */
#define HR_SCRIPT_EGYPTIAN_HIEROGLYPHS 1164409200

/**
 * The Imperial Aramaic script (`Armi`).
 */
#define HR_SCRIPT_IMPERIAL_ARAMAIC 1098018153

/**
 * The Inscriptional Pahlavi script (`Phli`).
 */
#define HR_SCRIPT_INSCRIPTIONAL_PAHLAVI 1349020777

/**
 * The Inscriptional Parthian script (`Prti`).
 */
#define HR_SCRIPT_INSCRIPTIONAL_PARTHIAN 1349678185

/**
 * The Javanese script (`Java`).
 */
#define HR_SCRIPT_JAVANESE 1247901281

/**
 * The Kaithi script (`Kthi`).
 */
#define HR_SCRIPT_KAITHI 1265920105

/**
 * The Lisu script (`Lisu`).
 */
#define HR_SCRIPT_LISU 1281979253

/**
 * The Meetei Mayek script (`Mtei`).
 */
#define HR_SCRIPT_MEETEI_MAYEK 1299473769

/**
 * The Old South Arabian script (`Sarb`).
 */
#define HR_SCRIPT_OLD_SOUTH_ARABIAN 1398895202

/**
 * The Old Turkic script (`Orkh`).
 */
#define HR_SCRIPT_OLD_TURKIC 1332898664

/**
 * The Samaritan script (`Samr`).
 */
#define HR_SCRIPT_SAMARITAN 1398893938

/**
 * The Tai Tham script (`Lana`).
 */
#define HR_SCRIPT_TAI_THAM 1281453665

/**
 * The Tai Viet script (`Tavt`).
 */
#define HR_SCRIPT_TAI_VIET 1415673460

/**
 * The Batak script (`Batk`).
 */
#define HR_SCRIPT_BATAK 1113683051

/**
 * The Brahmi script (`Brah`).
 */
#define HR_SCRIPT_BRAHMI 1114792296

/**
 * The Mandaic script (`Mand`).
 */
#define HR_SCRIPT_MANDAIC 1298230884

/**
 * The Chakma script (`Cakm`).
 */
#define HR_SCRIPT_CHAKMA 1130457965

/**
 * The Meroitic Cursive script (`Merc`).
 */
#define HR_SCRIPT_MEROITIC_CURSIVE 1298494051

/**
 * The Meroitic Hieroglyphs script (`Mero`).
 */
#define HR_SCRIPT_MEROITIC_HIEROGLYPHS 1298494063

/**
 * The Miao script (`Plrd`).
 */
#define HR_SCRIPT_MIAO 1349284452

/**
 * The Sharada script (`Shrd`).
 */
#define HR_SCRIPT_SHARADA 1399353956

/**
 * The Sora Sompeng script (`Sora`).
 */
#define HR_SCRIPT_SORA_SOMPENG 1399812705

/**
 * The Takri script (`Takr`).
 */
#define HR_SCRIPT_TAKRI 1415670642

/**
 * The Bassa Vah script (`Bass`).
 */
#define HR_SCRIPT_BASSA_VAH 1113682803

/**
 * The Caucasian Albanian script (`Aghb`).
 */
#define HR_SCRIPT_CAUCASIAN_ALBANIAN 1097295970

/**
 * The Duployan script (`Dupl`).
 */
#define HR_SCRIPT_DUPLOYAN 1148547180

/**
 * The Elbasan script (`Elba`).
 */
#define HR_SCRIPT_ELBASAN 1164730977

/**
 * The Grantha script (`Gran`).
 */
#define HR_SCRIPT_GRANTHA 1198678382

/**
 * The Khojki script (`Khoj`).
 */
#define HR_SCRIPT_KHOJKI 1265135466

/**
 * The Khudawadi script (`Sind`).
 */
#define HR_SCRIPT_KHUDAWADI 1399418468

/**
 * The Linear A script (`Lina`).
 */
#define HR_SCRIPT_LINEAR_A 1281977953

/**
 * The Mahajani script (`Mahj`).
 */
#define HR_SCRIPT_MAHAJANI 1298229354

/**
 * The Manichaean script (`Mani`).
 */
#define HR_SCRIPT_MANICHAEAN 1298230889

/**
 * The Mende Kikakui script (`Mend`).
 */
#define HR_SCRIPT_MENDE_KIKAKUI 1298493028

/**
 * The Modi script (`Modi`).
 */
#define HR_SCRIPT_MODI 1299145833

/**
 * The Mro script (`Mroo`).
 */
#define HR_SCRIPT_MRO 1299345263

/**
 * The Nabataean script (`Nbat`).
 */
#define HR_SCRIPT_NABATAEAN 1315070324

/**
 * The Old North Arabian script (`Narb`).
 */
#define HR_SCRIPT_OLD_NORTH_ARABIAN 1315009122

/**
 * The Old Permic script (`Perm`).
 */
#define HR_SCRIPT_OLD_PERMIC 1348825709

/**
 * The Pahawh Hmong script (`Hmng`).
 */
#define HR_SCRIPT_PAHAWH_HMONG 1215131239

/**
 * The Palmyrene script (`Palm`).
 */
#define HR_SCRIPT_PALMYRENE 1348562029

/**
 * The Pau Cin Hau script (`Pauc`).
 */
#define HR_SCRIPT_PAU_CIN_HAU 1348564323

/**
 * The Psalter Pahlavi script (`Phlp`).
 */
#define HR_SCRIPT_PSALTER_PAHLAVI 1349020784

/**
 * The Siddham script (`Sidd`).
 */
#define HR_SCRIPT_SIDDHAM 1399415908

/**
 * The Tirhuta script (`Tirh`).
 */
#define HR_SCRIPT_TIRHUTA 1416196712

/**
 * The Warang Citi script (`Wara`).
 */
#define HR_SCRIPT_WARANG_CITI 1466004065

/**
 * The Ahom script (`Ahom`).
 */
#define HR_SCRIPT_AHOM 1097363309

/**
 * The Anatolian Hieroglyphs script (`Hluw`).
 */
#define HR_SCRIPT_ANATOLIAN_HIEROGLYPHS 1215067511

/**
 * The Hatran script (`Hatr`).
 */
#define HR_SCRIPT_HATRAN 1214346354

/**
 * The Multani script (`Mult`).
 */
#define HR_SCRIPT_MULTANI 1299541108

/**
 * The Old Hungarian script (`Hung`).
 */
#define HR_SCRIPT_OLD_HUNGARIAN 1215655527

/**
 * The Signwriting script (`Sgnw`).
 */
#define HR_SCRIPT_SIGNWRITING 1399287415

/**
 * The Adlam script (`Adlm`).
 */
#define HR_SCRIPT_ADLAM 1097100397

/**
 * The Bhaiksuki script (`Bhks`).
 */
#define HR_SCRIPT_BHAIKSUKI 1114139507

/**
 * The Marchen script (`Marc`).
 */
#define HR_SCRIPT_MARCHEN 1298231907

/**
 * The Osage script (`Osge`).
 */
#define HR_SCRIPT_OSAGE 1332963173

/**
 * The Tangut script (`Tang`).
 */
#define HR_SCRIPT_TANGUT 1415671399

/**
 * The Newa script (`Newa`).
 */
#define HR_SCRIPT_NEWA 1315272545

/**
 * The Masaram Gondi script (`Gonm`).
 */
#define HR_SCRIPT_MASARAM_GONDI 1198485101

/**
 * The Nushu script (`Nshu`).
 */
#define HR_SCRIPT_NUSHU 1316186229

/**
 * The Soyombo script (`Soyo`).
 */
#define HR_SCRIPT_SOYOMBO 1399814511

/**
 * The Zanabazar Square script (`Zanb`).
 */
#define HR_SCRIPT_ZANABAZAR_SQUARE 1516334690

/**
 * The Dogra script (`Dogr`).
 */
#define HR_SCRIPT_DOGRA 1148151666

/**
 * The Gunjala Gondi script (`Gong`).
 */
#define HR_SCRIPT_GUNJALA_GONDI 1198485095

/**
 * The Hanifi Rohingya script (`Rohg`).
 */
#define HR_SCRIPT_HANIFI_ROHINGYA 1383032935

/**
 * The Makasar script (`Maka`).
 */
#define HR_SCRIPT_MAKASAR 1298230113

/**
 * The Medefaidrin script (`Medf`).
 */
#define HR_SCRIPT_MEDEFAIDRIN 1298490470

/**
 * The Old Sogdian script (`Sogo`).
 */
#define HR_SCRIPT_OLD_SOGDIAN 1399809903

/**
 * The Sogdian script (`Sogd`).
 */
#define HR_SCRIPT_SOGDIAN 1399809892

/**
 * The Elymaic script (`Elym`).
 */
#define HR_SCRIPT_ELYMAIC 1164736877

/**
 * The Nandinagari script (`Nand`).
 */
#define HR_SCRIPT_NANDINAGARI 1315008100

/**
 * The Nyiakeng Puachue Hmong script (`Hmnp`).
 */
#define HR_SCRIPT_NYIAKENG_PUACHUE_HMONG 1215131248

/**
 * The Wancho script (`Wcho`).
 */
#define HR_SCRIPT_WANCHO 1466132591

/**
 * The Chorasmian script (`Chrs`).
 */
#define HR_SCRIPT_CHORASMIAN 1130918515

/**
 * The Dives Akuru script (`Diak`).
 */
#define HR_SCRIPT_DIVES_AKURU 1147756907

/**
 * The Khitan Small Script script (`Kits`).
 */
#define HR_SCRIPT_KHITAN_SMALL_SCRIPT 1265202291

/**
 * The Yezidi script (`Yezi`).
 */
#define HR_SCRIPT_YEZIDI 1499822697

/**
 * The Cypro Minoan script (`Cpmn`).
 */
#define HR_SCRIPT_CYPRO_MINOAN 1131441518

/**
 * The Old Uyghur script (`Ougr`).
 */
#define HR_SCRIPT_OLD_UYGHUR 1333094258

/**
 * The Tangsa script (`Tnsa`).
 */
#define HR_SCRIPT_TANGSA 1416524641

/**
 * The Toto script (`Toto`).
 */
#define HR_SCRIPT_TOTO 1416590447

/**
 * The Vithkuqi script (`Vith`).
 */
#define HR_SCRIPT_VITHKUQI 1449751656

/**
 * The Kawi script (`Kawi`).
 */
#define HR_SCRIPT_KAWI 1264678761

/**
 * The Nag Mundari script (`Nagm`).
 */
#define HR_SCRIPT_NAG_MUNDARI 1315006317

/**
 * The Garay script (`Gara`).
 */
#define HR_SCRIPT_GARAY 1197568609

/**
 * The Gurung Khema script (`Gukh`).
 */
#define HR_SCRIPT_GURUNG_KHEMA 1198877544

/**
 * The Kirat Rai script (`Krai`).
 */
#define HR_SCRIPT_KIRAT_RAI 1265787241

/**
 * The Ol Onal script (`Onao`).
 */
#define HR_SCRIPT_OL_ONAL 1332633967

/**
 * The Sunuwar script (`Sunu`).
 */
#define HR_SCRIPT_SUNUWAR 1400204917

/**
 * The Todhri script (`Todr`).
 */
#define HR_SCRIPT_TODHRI 1416586354

/**
 * The Tulu Tigalari script (`Tutg`).
 */
#define HR_SCRIPT_TULU_TIGALARI 1416983655

/**
 * The Beria Erfe script (`Berf`).
 */
#define HR_SCRIPT_BERIA_ERFE 1113944678

/**
 * The Sidetic script (`Sidt`).
 */
#define HR_SCRIPT_SIDETIC 1399415924

/**
 * The Tai Yo script (`Tayo`).
 */
#define HR_SCRIPT_TAI_YO 1415674223

/**
 * The Tolong Siki script (`Tols`).
 */
#define HR_SCRIPT_TOLONG_SIKI 1416588403

/**
 * The Math script (`Zmth`).
 */
#define HR_SCRIPT_MATH 1517122664

/**
 * The Myanmar Zawgyi script (`Qaag`).
 */
#define HR_SCRIPT_MYANMAR_ZAWGYI 1365336423

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates a blob over `length` bytes at `data`.
 *
 * With [`hr_memory_mode_t::HR_MEMORY_MODE_DUPLICATE`] the data is copied and
 * `destroy` is called before returning. Otherwise the blob borrows the data,
 * which must stay valid and unchanged until `destroy` is invoked.
 *
 * Never returns `NULL`; on failure it returns the empty blob.
 *
 * # Safety
 *
 * `data` must point to `length` readable bytes. `destroy`, if given, must be
 * safe to call from any thread.
 */
struct hr_blob_t *hr_blob_create(const char *data,
                                 unsigned int length,
                                 enum hr_memory_mode_t mode,
                                 void *user_data,
                                 hr_destroy_func_t destroy);

/**
 * Creates a blob, returning `NULL` rather than the empty blob on failure.
 *
 * # Safety
 *
 * See [`hr_blob_create`].
 */
struct hr_blob_t *hr_blob_create_or_fail(const char *data,
                                         unsigned int length,
                                         enum hr_memory_mode_t mode,
                                         void *user_data,
                                         hr_destroy_func_t destroy);

/**
 * Creates a blob over the contents of a file.
 *
 * Never returns `NULL`; on failure it returns the empty blob.
 *
 * # Safety
 *
 * `file_name` must be a NUL-terminated string.
 */
struct hr_blob_t *hr_blob_create_from_file(const char *file_name);

/**
 * Creates a blob over the contents of a file, returning `NULL` on failure.
 *
 * # Safety
 *
 * `file_name` must be a NUL-terminated string.
 */
struct hr_blob_t *hr_blob_create_from_file_or_fail(const char *file_name);

/**
 * Creates a blob over a range of another blob, sharing its storage.
 *
 * The range is clamped to the parent's bounds. Never returns `NULL`.
 *
 * # Safety
 *
 * `parent` must be `NULL` or a live blob.
 */
struct hr_blob_t *hr_blob_create_sub_blob(struct hr_blob_t *parent,
                                          unsigned int offset,
                                          unsigned int length);

/**
 * Returns a new blob holding a private copy of `blob`'s data.
 *
 * Returns `NULL` if the blob is empty or the copy could not be made.
 *
 * # Safety
 *
 * `blob` must be `NULL` or a live blob.
 */
struct hr_blob_t *hr_blob_copy_writable_or_fail(struct hr_blob_t *blob);

/**
 * Returns the immortal empty blob.
 */
struct hr_blob_t *hr_blob_get_empty(void);

/**
 * Increments a blob's reference count.
 *
 * # Safety
 *
 * `blob` must be `NULL` or a live blob.
 */
struct hr_blob_t *hr_blob_reference(struct hr_blob_t *blob);

/**
 * Decrements a blob's reference count, freeing it at zero.
 *
 * # Safety
 *
 * `blob` must be `NULL` or a live blob, and the caller must own the
 * reference being released.
 */
void hr_blob_destroy(struct hr_blob_t *blob);

/**
 * Attaches user data to a blob.
 *
 * # Safety
 *
 * `blob` must be `NULL` or a live blob, and `key` must outlive it.
 */
hr_bool_t hr_blob_set_user_data(struct hr_blob_t *blob,
                                const struct hr_user_data_key_t *key,
                                void *data,
                                hr_destroy_func_t destroy,
                                hr_bool_t replace);

/**
 * Retrieves user data previously attached to a blob.
 *
 * # Safety
 *
 * `blob` must be `NULL` or a live blob.
 */
void *hr_blob_get_user_data(struct hr_blob_t *blob, const struct hr_user_data_key_t *key);

/**
 * Marks a blob immutable.
 *
 * # Safety
 *
 * `blob` must be `NULL` or a live blob.
 */
void hr_blob_make_immutable(struct hr_blob_t *blob);

/**
 * Returns whether a blob has been marked immutable.
 *
 * # Safety
 *
 * `blob` must be `NULL` or a live blob.
 */
hr_bool_t hr_blob_is_immutable(struct hr_blob_t *blob);

/**
 * Returns the length of a blob's data, in bytes.
 *
 * # Safety
 *
 * `blob` must be `NULL` or a live blob.
 */
unsigned int hr_blob_get_length(struct hr_blob_t *blob);

/**
 * Returns a blob's data, writing its length to `length` when non-`NULL`.
 *
 * # Safety
 *
 * `blob` must be `NULL` or a live blob, and `length` must be `NULL` or
 * writable.
 */
const char *hr_blob_get_data(struct hr_blob_t *blob, unsigned int *length);

/**
 * Always returns `NULL`, writing zero to `length`.
 *
 * Blobs in this library are read-only, since the shaping API never needs to
 * modify font data in place. Use [`hr_blob_copy_writable_or_fail`] to obtain
 * a private, mutable copy instead.
 *
 * # Safety
 *
 * `length` must be `NULL` or writable.
 */
char *hr_blob_get_data_writable(struct hr_blob_t *_blob, unsigned int *length);

/**
 * Creates an empty buffer.
 */
struct hr_buffer_t *hr_buffer_create(void);

/**
 * Creates an empty buffer carrying the same properties as `src`.
 *
 * # Safety
 *
 * `src` must be `NULL` or a live buffer.
 */
struct hr_buffer_t *hr_buffer_create_similar(struct hr_buffer_t *src);

/**
 * Returns the immortal empty buffer.
 */
struct hr_buffer_t *hr_buffer_get_empty(void);

/**
 * Increments a buffer's reference count.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
struct hr_buffer_t *hr_buffer_reference(struct hr_buffer_t *buffer);

/**
 * Decrements a buffer's reference count, freeing it at zero.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer, and the caller must own the
 * reference being released.
 */
void hr_buffer_destroy(struct hr_buffer_t *buffer);

/**
 * Attaches user data to a buffer.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer, and `key` must outlive it.
 */
hr_bool_t hr_buffer_set_user_data(struct hr_buffer_t *buffer,
                                  const struct hr_user_data_key_t *key,
                                  void *data,
                                  hr_destroy_func_t destroy,
                                  hr_bool_t replace);

/**
 * Retrieves user data previously attached to a buffer.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
void *hr_buffer_get_user_data(struct hr_buffer_t *buffer, const struct hr_user_data_key_t *key);

/**
 * Clears a buffer's contents and resets its properties to their defaults.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
void hr_buffer_reset(struct hr_buffer_t *buffer);

/**
 * Clears a buffer's contents, keeping its properties and its allocation.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
void hr_buffer_clear_contents(struct hr_buffer_t *buffer);

/**
 * Grows a buffer so it can hold at least `size` items without reallocating.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
hr_bool_t hr_buffer_pre_allocate(struct hr_buffer_t *buffer, unsigned int size);

/**
 * Returns whether every allocation on a buffer has succeeded.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
hr_bool_t hr_buffer_allocation_successful(struct hr_buffer_t *buffer);

/**
 * Appends one codepoint to a buffer with the given cluster value.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
void hr_buffer_add(struct hr_buffer_t *buffer, hr_codepoint_t codepoint, unsigned int cluster);

/**
 * Appends UTF-8 text to a buffer.
 *
 * Only `text[item_offset .. item_offset + item_length]` is added; the text
 * around it becomes shaping context. A negative `item_length` means "to the
 * end", and a negative `text_length` means `text` is NUL-terminated. Cluster
 * values are byte offsets into `text`.
 *
 * # Safety
 *
 * `text` must point to `text_length` readable bytes, or be NUL-terminated
 * when `text_length` is negative.
 */
void hr_buffer_add_utf8(struct hr_buffer_t *buffer,
                        const char *text,
                        int text_length,
                        unsigned int item_offset,
                        int item_length);

/**
 * Appends UTF-32 codepoints to a buffer.
 *
 * Follows the same `item_offset` / `item_length` convention as
 * [`hr_buffer_add_utf8`], with cluster values counted in codepoints.
 *
 * # Safety
 *
 * `text` must point to `text_length` readable codepoints, or be terminated
 * by a zero when `text_length` is negative.
 */
void hr_buffer_add_utf32(struct hr_buffer_t *buffer,
                         const uint32_t *text,
                         int text_length,
                         unsigned int item_offset,
                         int item_length);

/**
 * Appends codepoints to a buffer.
 *
 * Identical to [`hr_buffer_add_utf32`]; both are provided to match HarfBuzz.
 *
 * # Safety
 *
 * See [`hr_buffer_add_utf32`].
 */
void hr_buffer_add_codepoints(struct hr_buffer_t *buffer,
                              const hr_codepoint_t *text,
                              int text_length,
                              unsigned int item_offset,
                              int item_length);

/**
 * Appends a range of one buffer's items to another.
 *
 * # Safety
 *
 * Both buffers must be `NULL` or live, and must not be the same buffer.
 */
void hr_buffer_append(struct hr_buffer_t *buffer,
                      const struct hr_buffer_t *source,
                      unsigned int start,
                      unsigned int end);

/**
 * Returns what a buffer currently holds.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
enum hr_buffer_content_type_t hr_buffer_get_content_type(struct hr_buffer_t *buffer);

/**
 * Relabels what a buffer holds, without clearing it.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
void hr_buffer_set_content_type(struct hr_buffer_t *buffer,
                                enum hr_buffer_content_type_t content_type);

/**
 * Sets a buffer's text direction.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
void hr_buffer_set_direction(struct hr_buffer_t *buffer, hr_direction_t direction);

/**
 * Returns a buffer's text direction.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
hr_direction_t hr_buffer_get_direction(struct hr_buffer_t *buffer);

/**
 * Sets a buffer's script.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
void hr_buffer_set_script(struct hr_buffer_t *buffer, hr_script_t script);

/**
 * Returns a buffer's script.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
hr_script_t hr_buffer_get_script(struct hr_buffer_t *buffer);

/**
 * Sets a buffer's language.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer, and `language` must be `NULL` or
 * a value returned by `hr_language_from_string`.
 */
void hr_buffer_set_language(struct hr_buffer_t *buffer, hr_language_t language);

/**
 * Returns a buffer's language, or `NULL` if it has none.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
hr_language_t hr_buffer_get_language(struct hr_buffer_t *buffer);

/**
 * Sets a buffer's flags.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
void hr_buffer_set_flags(struct hr_buffer_t *buffer, hr_buffer_flags_t flags);

/**
 * Returns a buffer's flags.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
hr_buffer_flags_t hr_buffer_get_flags(struct hr_buffer_t *buffer);

/**
 * Sets a buffer's cluster level.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
void hr_buffer_set_cluster_level(struct hr_buffer_t *buffer,
                                 enum hr_buffer_cluster_level_t cluster_level);

/**
 * Returns a buffer's cluster level.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
enum hr_buffer_cluster_level_t hr_buffer_get_cluster_level(struct hr_buffer_t *buffer);

/**
 * Returns the number of items in a buffer.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
unsigned int hr_buffer_get_length(struct hr_buffer_t *buffer);

/**
 * Sets the number of items in a buffer, zero-filling any growth.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
hr_bool_t hr_buffer_set_length(struct hr_buffer_t *buffer, unsigned int length);

/**
 * Returns a buffer's items, writing their count to `length`.
 *
 * Before shaping, each item's `codepoint` holds an input character. The
 * pointer stays valid until the buffer's contents change.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer, and `length` must be `NULL` or
 * writable.
 */
struct hr_glyph_info_t *hr_buffer_get_glyph_infos(struct hr_buffer_t *buffer, unsigned int *length);

/**
 * Returns a buffer's glyph positions, writing their count to `length`.
 *
 * Positions are allocated and zeroed on demand if the buffer has not been
 * shaped. The pointer stays valid until the buffer's contents change.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer, and `length` must be `NULL` or
 * writable.
 */
struct hr_glyph_position_t *hr_buffer_get_glyph_positions(struct hr_buffer_t *buffer,
                                                          unsigned int *length);

/**
 * Returns whether a buffer has glyph positions, which is true after shaping.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
hr_bool_t hr_buffer_has_positions(struct hr_buffer_t *buffer);

/**
 * Returns the flags shaping attached to one item.
 *
 * # Safety
 *
 * `info` must be `NULL` or point to a readable item.
 */
hr_glyph_flags_t hr_glyph_info_get_glyph_flags(const struct hr_glyph_info_t *info);

/**
 * Sets the glyph used in place of invisible characters.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
void hr_buffer_set_invisible_glyph(struct hr_buffer_t *buffer, hr_codepoint_t invisible);

/**
 * Returns the glyph used in place of invisible characters, or zero.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
hr_codepoint_t hr_buffer_get_invisible_glyph(struct hr_buffer_t *buffer);

/**
 * Sets the glyph used in place of variation selectors the font lacks.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
void hr_buffer_set_not_found_variation_selector_glyph(struct hr_buffer_t *buffer,
                                                      hr_codepoint_t glyph);

/**
 * Returns the glyph used in place of variation selectors the font lacks.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
hr_codepoint_t hr_buffer_get_not_found_variation_selector_glyph(struct hr_buffer_t *buffer);

/**
 * Writes a buffer's direction, script and language into `props`.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer, and `props` must be `NULL` or
 * writable.
 */
void hr_buffer_get_segment_properties(struct hr_buffer_t *buffer,
                                      struct hr_segment_properties_t *props);

/**
 * Sets a buffer's direction, script and language at once.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer, and `props` must be `NULL` or
 * readable.
 */
void hr_buffer_set_segment_properties(struct hr_buffer_t *buffer,
                                      const struct hr_segment_properties_t *props);

/**
 * Fills in whichever of direction, script and language are still unset, by
 * inspecting the buffer's contents.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
void hr_buffer_guess_segment_properties(struct hr_buffer_t *buffer);

/**
 * Reverses a buffer's contents.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
void hr_buffer_reverse(struct hr_buffer_t *buffer);

/**
 * Reverses part of a buffer's contents.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
void hr_buffer_reverse_range(struct hr_buffer_t *buffer, unsigned int start, unsigned int end);

/**
 * Reverses a buffer's contents, keeping each cluster's items in order.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
void hr_buffer_reverse_clusters(struct hr_buffer_t *buffer);

/**
 * Resets every item's cluster value to its index.
 *
 * # Safety
 *
 * `buffer` must be `NULL` or a live buffer.
 */
void hr_buffer_reset_clusters(struct hr_buffer_t *buffer);

/**
 * Returns the serialization format matching a name, such as `"text"`.
 *
 * # Safety
 *
 * See `hr_tag_from_string`.
 */
enum hr_buffer_serialize_format_t hr_buffer_serialize_format_from_string(const char *str_, int len);

/**
 * Returns the name of a serialization format, or `NULL` if it is invalid.
 */
const char *hr_buffer_serialize_format_to_string(enum hr_buffer_serialize_format_t format);

/**
 * Returns the serialization formats this library supports, as a
 * `NULL`-terminated array of names.
 */
const char *const *hr_buffer_serialize_list_formats(void);

/**
 * Writes a human-readable form of `buffer[start..end]` into `buf`.
 *
 * Returns the number of items serialized, writing the number of bytes used to
 * `buf_consumed`. Only
 * [`hr_buffer_serialize_format_t::HR_BUFFER_SERIALIZE_FORMAT_TEXT`] is
 * supported; any other format serializes nothing.
 *
 * # Safety
 *
 * `buffer` and `font` must be `NULL` or live, `buf` must point to `buf_size`
 * writable bytes, and `buf_consumed` must be `NULL` or writable.
 */
unsigned int hr_buffer_serialize_glyphs(struct hr_buffer_t *buffer,
                                        unsigned int start,
                                        unsigned int end,
                                        char *buf,
                                        unsigned int buf_size,
                                        unsigned int *buf_consumed,
                                        struct hr_font_t *font,
                                        enum hr_buffer_serialize_format_t format,
                                        hr_buffer_serialize_flags_t flags);

/**
 * Converts a string into a tag, padding with spaces and truncating past four
 * bytes.
 *
 * Pass a negative `len` for a NUL-terminated string.
 *
 * # Safety
 *
 * See [`str_from_raw`].
 */
hr_tag_t hr_tag_from_string(const char *str_, int len);

/**
 * Writes a tag's four bytes into `buf`. No terminating NUL is written.
 *
 * # Safety
 *
 * `buf` must point to at least four writable bytes.
 */
void hr_tag_to_string(hr_tag_t tag, char *buf);

/**
 * Parses a direction from its name, matching on the first letter only.
 *
 * # Safety
 *
 * See [`str_from_raw`].
 */
hr_direction_t hr_direction_from_string(const char *str_, int len);

/**
 * Returns the name of a direction, as a NUL-terminated static string.
 */
const char *hr_direction_to_string(hr_direction_t direction);

/**
 * Returns whether a direction is horizontal.
 */
hr_bool_t hr_direction_is_horizontal(hr_direction_t direction);

/**
 * Returns whether a direction is vertical.
 */
hr_bool_t hr_direction_is_vertical(hr_direction_t direction);

/**
 * Returns whether a direction runs forwards (left-to-right or top-to-bottom).
 */
hr_bool_t hr_direction_is_forward(hr_direction_t direction);

/**
 * Returns whether a direction runs backwards.
 */
hr_bool_t hr_direction_is_backward(hr_direction_t direction);

/**
 * Returns whether a direction is set at all.
 */
hr_bool_t hr_direction_is_valid(hr_direction_t direction);

/**
 * Returns the direction running opposite to the given one.
 */
hr_direction_t hr_direction_reverse(hr_direction_t direction);

/**
 * Converts an ISO 15924 tag into a script.
 */
hr_script_t hr_script_from_iso15924_tag(hr_tag_t tag);

/**
 * Parses a script from an ISO 15924 tag written as a string.
 *
 * # Safety
 *
 * See [`str_from_raw`].
 */
hr_script_t hr_script_from_string(const char *str_, int len);

/**
 * Returns a script's ISO 15924 tag.
 */
hr_tag_t hr_script_to_iso15924_tag(hr_script_t script);

/**
 * Returns the direction text in this script is usually set in.
 */
hr_direction_t hr_script_get_horizontal_direction(hr_script_t script);

/**
 * Interns a language from a BCP 47 tag.
 *
 * The returned value lives for the lifetime of the process and must not be
 * freed.
 *
 * # Safety
 *
 * See [`str_from_raw`].
 */
hr_language_t hr_language_from_string(const char *str_, int len);

/**
 * Returns a language's tag as a NUL-terminated string, or `NULL` when the
 * language is unset.
 * # Safety
 *
 * `language` must be `NULL` or a value returned by `hr_language_from_string`.
 */
const char *hr_language_to_string(hr_language_t language);

/**
 * Returns the process's default language, taken from the environment.
 */
hr_language_t hr_language_get_default(void);

/**
 * Returns whether `language` is the same as, or a more specific form of,
 * `specific`.
 * # Safety
 *
 * Both arguments must be `NULL` or values returned by
 * `hr_language_from_string`.
 */
hr_bool_t hr_language_matches(hr_language_t language, hr_language_t specific);

/**
 * Parses a feature from its string form, such as `kern`, `-liga` or
 * `aalt[3:5]=2`.
 *
 * Returns false, leaving `feature` untouched, if the string does not parse.
 *
 * # Safety
 *
 * See [`str_from_raw`]. `feature` must be `NULL` or writable.
 */
hr_bool_t hr_feature_from_string(const char *str_, int len, struct hr_feature_t *feature);

/**
 * Writes a feature's string form into `buf`, always NUL-terminating it.
 *
 * # Safety
 *
 * `feature` must be `NULL` or readable, and `buf` must point to `size`
 * writable bytes.
 */
void hr_feature_to_string(const struct hr_feature_t *feature, char *buf, unsigned int size);

/**
 * Parses a variation from its string form, such as `wght=700`.
 *
 * Returns false, leaving `variation` untouched, if the string does not parse.
 *
 * # Safety
 *
 * See [`str_from_raw`]. `variation` must be `NULL` or writable.
 */
hr_bool_t hr_variation_from_string(const char *str_, int len, struct hr_variation_t *variation);

/**
 * Writes a variation's string form into `buf`, always NUL-terminating it.
 *
 * # Safety
 *
 * `variation` must be `NULL` or readable, and `buf` must point to `size`
 * writable bytes.
 */
void hr_variation_to_string(const struct hr_variation_t *variation, char *buf, unsigned int size);

/**
 * Creates a face over the font at `index` within `blob`.
 *
 * The face takes its own reference to the blob. Never returns `NULL`; a blob
 * that does not parse yields the empty face.
 *
 * # Safety
 *
 * `blob` must be `NULL` or a live blob.
 */
struct hr_face_t *hr_face_create(struct hr_blob_t *blob, unsigned int index);

/**
 * Creates a face over a blob, returning `NULL` if it does not parse.
 *
 * # Safety
 *
 * `blob` must be `NULL` or a live blob.
 */
struct hr_face_t *hr_face_create_or_fail(struct hr_blob_t *blob, unsigned int index);

/**
 * Creates a face whose tables are supplied by a callback.
 *
 * The callback is invoked lazily, once per table, and may be called from any
 * thread; it and its user data must be safe to use concurrently. `destroy` is
 * called with `user_data` when the face is freed.
 *
 * Never returns `NULL`.
 *
 * # Safety
 *
 * `reference_table_func` must be safe to call with `user_data` from any
 * thread, and must return either `NULL` or a blob reference it gives up
 * ownership of.
 */
struct hr_face_t *hr_face_create_for_tables(hr_reference_table_func_t reference_table_func,
                                            void *user_data,
                                            hr_destroy_func_t destroy);

/**
 * Returns the immortal empty face.
 */
struct hr_face_t *hr_face_get_empty(void);

/**
 * Increments a face's reference count.
 *
 * # Safety
 *
 * `face` must be `NULL` or a live face.
 */
struct hr_face_t *hr_face_reference(struct hr_face_t *face);

/**
 * Decrements a face's reference count, freeing it at zero.
 *
 * # Safety
 *
 * `face` must be `NULL` or a live face, and the caller must own the
 * reference being released.
 */
void hr_face_destroy(struct hr_face_t *face);

/**
 * Attaches user data to a face.
 *
 * # Safety
 *
 * `face` must be `NULL` or a live face, and `key` must outlive it.
 */
hr_bool_t hr_face_set_user_data(struct hr_face_t *face,
                                const struct hr_user_data_key_t *key,
                                void *data,
                                hr_destroy_func_t destroy,
                                hr_bool_t replace);

/**
 * Retrieves user data previously attached to a face.
 *
 * # Safety
 *
 * `face` must be `NULL` or a live face.
 */
void *hr_face_get_user_data(struct hr_face_t *face, const struct hr_user_data_key_t *key);

/**
 * Marks a face immutable.
 *
 * # Safety
 *
 * `face` must be `NULL` or a live face.
 */
void hr_face_make_immutable(struct hr_face_t *face);

/**
 * Returns whether a face has been marked immutable.
 *
 * # Safety
 *
 * `face` must be `NULL` or a live face.
 */
hr_bool_t hr_face_is_immutable(struct hr_face_t *face);

/**
 * Returns the index this face was created with, within its collection.
 *
 * # Safety
 *
 * `face` must be `NULL` or a live face.
 */
unsigned int hr_face_get_index(struct hr_face_t *face);

/**
 * Returns a face's design units per em, or 1000 if it has no `head` table.
 *
 * # Safety
 *
 * `face` must be `NULL` or a live face.
 */
unsigned int hr_face_get_upem(struct hr_face_t *face);

/**
 * Returns the number of glyphs in a face.
 *
 * # Safety
 *
 * `face` must be `NULL` or a live face.
 */
unsigned int hr_face_get_glyph_count(struct hr_face_t *face);

/**
 * Returns the blob a face was created over, or the empty blob for a face
 * built from table callbacks.
 *
 * The caller owns the returned reference.
 *
 * # Safety
 *
 * `face` must be `NULL` or a live face.
 */
struct hr_blob_t *hr_face_reference_blob(struct hr_face_t *face);

/**
 * Returns the data of one table, or the empty blob if the face has no such
 * table.
 *
 * The caller owns the returned reference. For a blob-backed face the result
 * shares the face's storage rather than copying. For a face built from table
 * callbacks, this invokes the callback.
 *
 * # Safety
 *
 * `face` must be `NULL` or a live face.
 */
struct hr_blob_t *hr_face_reference_table(struct hr_face_t *face, hr_tag_t tag);

/**
 * Creates a font over a face.
 *
 * The font takes its own reference to the face. Its scale starts at the
 * face's units per em, so positions come out in font units until
 * [`hr_font_set_scale`] says otherwise.
 *
 * Never returns `NULL`; a face with no font data yields the empty font.
 *
 * # Safety
 *
 * `face` must be `NULL` or a live face.
 */
struct hr_font_t *hr_font_create(struct hr_face_t *face);

/**
 * Creates a font that starts out as a copy of `parent`.
 *
 * The sub-font holds a reference to its parent and inherits its scale, point
 * size, variation settings and callbacks; changing the sub-font afterwards
 * does not affect the parent.
 *
 * # Safety
 *
 * `parent` must be `NULL` or a live font.
 */
struct hr_font_t *hr_font_create_sub_font(struct hr_font_t *parent);

/**
 * Returns the immortal empty font.
 */
struct hr_font_t *hr_font_get_empty(void);

/**
 * Increments a font's reference count.
 *
 * # Safety
 *
 * `font` must be `NULL` or a live font.
 */
struct hr_font_t *hr_font_reference(struct hr_font_t *font);

/**
 * Decrements a font's reference count, freeing it at zero.
 *
 * # Safety
 *
 * `font` must be `NULL` or a live font, and the caller must own the
 * reference being released.
 */
void hr_font_destroy(struct hr_font_t *font);

/**
 * Attaches user data to a font.
 *
 * # Safety
 *
 * `font` must be `NULL` or a live font, and `key` must outlive it.
 */
hr_bool_t hr_font_set_user_data(struct hr_font_t *font,
                                const struct hr_user_data_key_t *key,
                                void *data,
                                hr_destroy_func_t destroy,
                                hr_bool_t replace);

/**
 * Retrieves user data previously attached to a font.
 *
 * # Safety
 *
 * `font` must be `NULL` or a live font.
 */
void *hr_font_get_user_data(struct hr_font_t *font, const struct hr_user_data_key_t *key);

/**
 * Marks a font immutable.
 *
 * # Safety
 *
 * `font` must be `NULL` or a live font.
 */
void hr_font_make_immutable(struct hr_font_t *font);

/**
 * Returns whether a font has been marked immutable.
 *
 * # Safety
 *
 * `font` must be `NULL` or a live font.
 */
hr_bool_t hr_font_is_immutable(struct hr_font_t *font);

/**
 * Returns the face a font was created over, without taking a reference.
 *
 * # Safety
 *
 * `font` must be `NULL` or a live font.
 */
struct hr_face_t *hr_font_get_face(struct hr_font_t *font);

/**
 * Returns a font's parent, or `NULL` if it is not a sub-font.
 *
 * # Safety
 *
 * `font` must be `NULL` or a live font.
 */
struct hr_font_t *hr_font_get_parent(struct hr_font_t *font);

/**
 * Sets a font's scale.
 *
 * Positions are reported as `font_units * scale / upem`, so a scale equal to
 * the face's units per em leaves values in font units. For 26.6 fixed point
 * at a given pixel size, pass `size * 64`.
 *
 * # Safety
 *
 * `font` must be `NULL` or a live font.
 */
void hr_font_set_scale(struct hr_font_t *font, int x_scale, int y_scale);

/**
 * Returns a font's scale.
 *
 * # Safety
 *
 * `font` must be `NULL` or a live font; `x_scale` and `y_scale` must be
 * `NULL` or writable.
 */
void hr_font_get_scale(struct hr_font_t *font, int *x_scale, int *y_scale);

/**
 * Sets a font's point size, used when applying the `trak` table.
 *
 * Pass zero to disable tracking.
 *
 * # Safety
 *
 * `font` must be `NULL` or a live font.
 */
void hr_font_set_ptem(struct hr_font_t *font, float ptem);

/**
 * Returns a font's point size, or zero if none is set.
 *
 * # Safety
 *
 * `font` must be `NULL` or a live font.
 */
float hr_font_get_ptem(struct hr_font_t *font);

/**
 * Sets a font's variation settings, in user space.
 *
 * Axes that are not named are reset to their default values, so this
 * replaces any previous variation settings rather than adding to them.
 *
 * # Safety
 *
 * `font` must be `NULL` or a live font, and `variations` must point to
 * `variations_length` readable entries.
 */
void hr_font_set_variations(struct hr_font_t *font,
                            const struct hr_variation_t *variations,
                            unsigned int variations_length);

/**
 * Sets a font's variation settings from normalized coordinates.
 *
 * Coordinates are 2.14 fixed point values in axis order. Missing axes take
 * their default value; extra coordinates are ignored.
 *
 * # Safety
 *
 * `font` must be `NULL` or a live font, and `coords` must point to
 * `coords_length` readable entries.
 */
void hr_font_set_var_coords_normalized(struct hr_font_t *font,
                                       const int *coords,
                                       unsigned int coords_length);

/**
 * Returns a font's normalized coordinates, writing their count to `length`.
 *
 * The returned pointer stays valid until the font's variation settings change
 * or the font is freed.
 *
 * # Safety
 *
 * `font` must be `NULL` or a live font, and `length` must be `NULL` or
 * writable.
 */
const int *hr_font_get_var_coords_normalized(struct hr_font_t *font, unsigned int *length);

/**
 * Sets a font's variation settings from a named instance in the `fvar` table.
 *
 * An index that does not exist resets the settings to their defaults.
 *
 * # Safety
 *
 * `font` must be `NULL` or a live font.
 */
void hr_font_set_var_named_instance(struct hr_font_t *font, unsigned int instance);

/**
 * Sets the callbacks a font uses during shaping.
 *
 * The font takes a reference to `ffuncs` and takes ownership of `font_data`,
 * releasing it through `destroy` when the callbacks are replaced or the font
 * is freed. Pass `NULL` for `ffuncs` to go back to the built-in callbacks.
 *
 * As in HarfBuzz, an installed funcs object is authoritative: it is not
 * blended with the built-in callbacks, and any callback it leaves unset
 * reports nothing available, giving glyph 0, a zero advance and no extents.
 * Populate every callback you need before installing the object.
 *
 * Callbacks are handed the font they were installed on so they can read its
 * scale and variation settings. They must not modify it, nor free it, while
 * shaping is under way; [`hr_font_make_immutable`] is a convenient way to
 * guarantee that.
 *
 * # Safety
 *
 * `font` must be `NULL` or a live font, `ffuncs` must be `NULL` or live, and
 * the callbacks must be safe to call with `font_data` from any thread.
 */
void hr_font_set_funcs(struct hr_font_t *font,
                       struct hr_font_funcs_t *ffuncs,
                       void *font_data,
                       hr_destroy_func_t destroy);

/**
 * Maps a Unicode scalar value to a glyph, returning false if the font has
 * none.
 *
 * This consults the font's `cmap` directly and does not run the callbacks set
 * by [`hr_font_set_funcs`].
 *
 * # Safety
 *
 * `font` must be `NULL` or a live font, and `glyph` must be `NULL` or
 * writable.
 */
hr_bool_t hr_font_get_nominal_glyph(struct hr_font_t *font,
                                    hr_codepoint_t unicode,
                                    hr_codepoint_t *glyph);

/**
 * Maps a Unicode scalar value and variation selector to a glyph, returning
 * false if the font has none.
 *
 * This consults the font's `cmap` directly and does not run the callbacks set
 * by [`hr_font_set_funcs`].
 *
 * # Safety
 *
 * `font` must be `NULL` or a live font, and `glyph` must be `NULL` or
 * writable.
 */
hr_bool_t hr_font_get_variation_glyph(struct hr_font_t *font,
                                      hr_codepoint_t unicode,
                                      hr_codepoint_t variation_selector,
                                      hr_codepoint_t *glyph);

/**
 * Creates an empty set of font callbacks.
 */
struct hr_font_funcs_t *hr_font_funcs_create(void);

/**
 * Returns the immortal empty set of font callbacks.
 */
struct hr_font_funcs_t *hr_font_funcs_get_empty(void);

/**
 * Increments the reference count of a set of font callbacks.
 *
 * # Safety
 *
 * `ffuncs` must be `NULL` or live.
 */
struct hr_font_funcs_t *hr_font_funcs_reference(struct hr_font_funcs_t *ffuncs);

/**
 * Decrements the reference count, freeing at zero and running every
 * registered destroy callback.
 *
 * # Safety
 *
 * `ffuncs` must be `NULL` or live, and the caller must own the reference.
 */
void hr_font_funcs_destroy(struct hr_font_funcs_t *ffuncs);

/**
 * Attaches user data to a set of font callbacks.
 *
 * # Safety
 *
 * `ffuncs` must be `NULL` or live, and `key` must outlive it.
 */
hr_bool_t hr_font_funcs_set_user_data(struct hr_font_funcs_t *ffuncs,
                                      const struct hr_user_data_key_t *key,
                                      void *data,
                                      hr_destroy_func_t destroy,
                                      hr_bool_t replace);

/**
 * Retrieves user data attached to a set of font callbacks.
 *
 * # Safety
 *
 * `ffuncs` must be `NULL` or live.
 */
void *hr_font_funcs_get_user_data(struct hr_font_funcs_t *ffuncs,
                                  const struct hr_user_data_key_t *key);

/**
 * Marks a set of font callbacks immutable.
 *
 * # Safety
 *
 * `ffuncs` must be `NULL` or live.
 */
void hr_font_funcs_make_immutable(struct hr_font_funcs_t *ffuncs);

/**
 * Returns whether a set of font callbacks has been marked immutable.
 *
 * # Safety
 *
 * `ffuncs` must be `NULL` or live.
 */
hr_bool_t hr_font_funcs_is_immutable(struct hr_font_funcs_t *ffuncs);

/**
 * Sets the callback mapping a Unicode scalar value to a glyph.
 *
 * Takes ownership of `user_data`, releasing it through `destroy` when the
 * callback is replaced or the funcs object is freed. Passing a `NULL` callback
 * clears any previously set one, after which it reports nothing available
 * rather than falling back to HarfRust's own implementation. Setting a
 * callback on an immutable object is ignored, and releases `user_data`
 * immediately.
 *
 * # Safety
 *
 * `ffuncs` must be `NULL` or live, and the callback must be safe to call with
 * `user_data` from any thread.
 */
void hr_font_funcs_set_nominal_glyph_func(struct hr_font_funcs_t *ffuncs,
                                          hr_font_get_nominal_glyph_func_t func,
                                          void *user_data,
                                          hr_destroy_func_t destroy);

/**
 * Sets the callback mapping a Unicode scalar value and variation selector
 * to a glyph.
 *
 * Takes ownership of `user_data`, releasing it through `destroy` when the
 * callback is replaced or the funcs object is freed. Passing a `NULL` callback
 * clears any previously set one, after which it reports nothing available
 * rather than falling back to HarfRust's own implementation. Setting a
 * callback on an immutable object is ignored, and releases `user_data`
 * immediately.
 *
 * # Safety
 *
 * `ffuncs` must be `NULL` or live, and the callback must be safe to call with
 * `user_data` from any thread.
 */
void hr_font_funcs_set_variation_glyph_func(struct hr_font_funcs_t *ffuncs,
                                            hr_font_get_variation_glyph_func_t func,
                                            void *user_data,
                                            hr_destroy_func_t destroy);

/**
 * Sets the callback returning a glyph's horizontal advance.
 *
 * Takes ownership of `user_data`, releasing it through `destroy` when the
 * callback is replaced or the funcs object is freed. Passing a `NULL` callback
 * clears any previously set one, after which it reports nothing available
 * rather than falling back to HarfRust's own implementation. Setting a
 * callback on an immutable object is ignored, and releases `user_data`
 * immediately.
 *
 * # Safety
 *
 * `ffuncs` must be `NULL` or live, and the callback must be safe to call with
 * `user_data` from any thread.
 */
void hr_font_funcs_set_glyph_h_advance_func(struct hr_font_funcs_t *ffuncs,
                                            hr_font_get_glyph_advance_func_t func,
                                            void *user_data,
                                            hr_destroy_func_t destroy);

/**
 * Sets the callback returning a glyph's vertical advance.
 *
 * Takes ownership of `user_data`, releasing it through `destroy` when the
 * callback is replaced or the funcs object is freed. Passing a `NULL` callback
 * clears any previously set one, after which it reports nothing available
 * rather than falling back to HarfRust's own implementation. Setting a
 * callback on an immutable object is ignored, and releases `user_data`
 * immediately.
 *
 * # Safety
 *
 * `ffuncs` must be `NULL` or live, and the callback must be safe to call with
 * `user_data` from any thread.
 */
void hr_font_funcs_set_glyph_v_advance_func(struct hr_font_funcs_t *ffuncs,
                                            hr_font_get_glyph_advance_func_t func,
                                            void *user_data,
                                            hr_destroy_func_t destroy);

/**
 * Sets the callback returning a glyph's vertical origin.
 *
 * Takes ownership of `user_data`, releasing it through `destroy` when the
 * callback is replaced or the funcs object is freed. Passing a `NULL` callback
 * clears any previously set one, after which it reports nothing available
 * rather than falling back to HarfRust's own implementation. Setting a
 * callback on an immutable object is ignored, and releases `user_data`
 * immediately.
 *
 * # Safety
 *
 * `ffuncs` must be `NULL` or live, and the callback must be safe to call with
 * `user_data` from any thread.
 */
void hr_font_funcs_set_glyph_v_origin_func(struct hr_font_funcs_t *ffuncs,
                                           hr_font_get_glyph_origin_func_t func,
                                           void *user_data,
                                           hr_destroy_func_t destroy);

/**
 * Sets the callback returning a glyph's ink extents.
 *
 * Takes ownership of `user_data`, releasing it through `destroy` when the
 * callback is replaced or the funcs object is freed. Passing a `NULL` callback
 * clears any previously set one, after which it reports nothing available
 * rather than falling back to HarfRust's own implementation. Setting a
 * callback on an immutable object is ignored, and releases `user_data`
 * immediately.
 *
 * # Safety
 *
 * `ffuncs` must be `NULL` or live, and the callback must be safe to call with
 * `user_data` from any thread.
 */
void hr_font_funcs_set_glyph_extents_func(struct hr_font_funcs_t *ffuncs,
                                          hr_font_get_glyph_extents_func_t func,
                                          void *user_data,
                                          hr_destroy_func_t destroy);

/**
 * Shapes a buffer with a font, applying the given features.
 *
 * The buffer's direction, script and language must be set beforehand; call
 * `hr_buffer_guess_segment_properties` to fill in whatever is missing, which
 * this does for the direction on your behalf. On return the buffer holds
 * glyphs.
 *
 * Call `hr_buffer_allocation_successful` if you want to know whether the
 * buffer ran out of room.
 *
 * # Aborts
 *
 * See [`hr_shape_full`].
 *
 * # Safety
 *
 * `font` and `buffer` must be `NULL` or live, and `features` must point to
 * `num_features` readable entries.
 */
void hr_shape(struct hr_font_t *font,
              struct hr_buffer_t *buffer,
              const struct hr_feature_t *features,
              unsigned int num_features);

/**
 * Shapes a buffer, selecting from a list of shaper names.
 *
 * This library has a single shaper, so `shaper_list` is honoured only to the
 * extent of failing when it names shapers that are all unavailable.
 *
 * Returns false only when no shaper could be run: `shaper_list` names none
 * that this library provides, or there is nothing to shape with. Shaping
 * itself never fails the call, which is what HarfBuzz does -- its
 * `hb_shape_full` reports failure only when it cannot find or instantiate a
 * shaper, and every shaper it does run returns true whatever became of the
 * buffer. So a buffer that ran past its length, operation or nesting limits
 * still returns true; call `hr_buffer_allocation_successful` to detect that.
 *
 * # Aborts
 *
 * Misusing the API aborts the process, as HarfBuzz's assertions do: passing a
 * buffer that already holds glyphs, or a font with nothing to shape with.
 * `hr_shape` returns nothing and so could not otherwise report these at
 * all.
 *
 * # Safety
 *
 * `font` and `buffer` must be `NULL` or live, `features` must point to
 * `num_features` readable entries, and `shaper_list` must be `NULL` or a
 * `NULL`-terminated array of NUL-terminated strings.
 */
hr_bool_t hr_shape_full(struct hr_font_t *font,
                        struct hr_buffer_t *buffer,
                        const struct hr_feature_t *features,
                        unsigned int num_features,
                        const char *const *shaper_list);

/**
 * Returns the shapers this library provides, as a `NULL`-terminated array of
 * names.
 */
const char *const *hr_shape_list_shapers(void);

/**
 * Returns the version of the underlying HarfRust library.
 *
 * # Safety
 *
 * Each of `major`, `minor` and `micro` must be `NULL` or writable.
 */
void hr_version(unsigned int *major, unsigned int *minor, unsigned int *micro);

/**
 * Returns the version of the underlying HarfRust library as a string.
 */
const char *hr_version_string(void);

/**
 * Returns whether the library is at least the given version.
 */
hr_bool_t hr_version_atleast(unsigned int major, unsigned int minor, unsigned int micro);

/**
 * Returns whether two sets of segment properties are the same.
 *
 * # Safety
 *
 * Both pointers must be `NULL` or readable.
 */
hr_bool_t hr_segment_properties_equal(const struct hr_segment_properties_t *a,
                                      const struct hr_segment_properties_t *b);

/**
 * Returns a hash of a set of segment properties.
 *
 * # Safety
 *
 * `p` must be `NULL` or readable.
 */
unsigned int hr_segment_properties_hash(const struct hr_segment_properties_t *p);

/**
 * Fills in whichever of `p`'s fields are unset from `src`.
 *
 * # Safety
 *
 * Both pointers must be `NULL` or readable, and `p` must be writable.
 */
void hr_segment_properties_overlay(struct hr_segment_properties_t *p,
                                   const struct hr_segment_properties_t *src);

/**
 * Builds a plan for shaping text with the given properties over a face.
 *
 * Never returns `NULL`; if a plan cannot be built, including when `props`
 * leaves the direction unset, this returns the empty plan.
 *
 * # Safety
 *
 * `face` must be `NULL` or a live face, `props` must be `NULL` or readable,
 * `user_features` must point to `num_user_features` readable entries, and
 * `shaper_list` must be `NULL` or a `NULL`-terminated array of NUL-terminated
 * strings.
 */
struct hr_shape_plan_t *hr_shape_plan_create(struct hr_face_t *face,
                                             const struct hr_segment_properties_t *props,
                                             const struct hr_feature_t *user_features,
                                             unsigned int num_user_features,
                                             const char *const *shaper_list);

/**
 * Builds a plan for a particular variation of a variable font.
 *
 * Coordinates are 2.14 fixed point values in axis order, as
 * `hr_font_get_var_coords_normalized` reports them. A plan built this way must
 * only be executed with a font set to the same coordinates.
 *
 * # Safety
 *
 * As [`hr_shape_plan_create`], and `coords` must be `NULL` or point to
 * `num_coords` readable entries.
 */
struct hr_shape_plan_t *hr_shape_plan_create2(struct hr_face_t *face,
                                              const struct hr_segment_properties_t *props,
                                              const struct hr_feature_t *user_features,
                                              unsigned int num_user_features,
                                              const int32_t *coords,
                                              unsigned int num_coords,
                                              const char *const *shaper_list);

/**
 * Builds a plan, reusing one from the face's cache when an equal plan is
 * already there.
 *
 * This is the cache [`hr_shape`](crate::hr_shape) uses, so a plan taken from
 * here costs nothing beyond the lookup once it has been built.
 *
 * # Safety
 *
 * See [`hr_shape_plan_create`].
 */
struct hr_shape_plan_t *hr_shape_plan_create_cached(struct hr_face_t *face,
                                                    const struct hr_segment_properties_t *props,
                                                    const struct hr_feature_t *user_features,
                                                    unsigned int num_user_features,
                                                    const char *const *shaper_list);

/**
 * Builds a plan for a particular variation, reusing one from the face's cache
 * when an equal plan is already there.
 *
 * # Safety
 *
 * See [`hr_shape_plan_create2`].
 */
struct hr_shape_plan_t *hr_shape_plan_create_cached2(struct hr_face_t *face,
                                                     const struct hr_segment_properties_t *props,
                                                     const struct hr_feature_t *user_features,
                                                     unsigned int num_user_features,
                                                     const int32_t *coords,
                                                     unsigned int num_coords,
                                                     const char *const *shaper_list);

/**
 * Returns the immortal empty plan, which shapes nothing.
 */
struct hr_shape_plan_t *hr_shape_plan_get_empty(void);

/**
 * Increments a plan's reference count.
 *
 * # Safety
 *
 * `shape_plan` must be `NULL` or a live plan.
 */
struct hr_shape_plan_t *hr_shape_plan_reference(struct hr_shape_plan_t *shape_plan);

/**
 * Decrements a plan's reference count, freeing it at zero.
 *
 * # Safety
 *
 * `shape_plan` must be `NULL` or a live plan, and the caller must own the
 * reference being released.
 */
void hr_shape_plan_destroy(struct hr_shape_plan_t *shape_plan);

/**
 * Attaches user data to a plan.
 *
 * # Safety
 *
 * `shape_plan` must be `NULL` or a live plan, and `key` must outlive it.
 */
hr_bool_t hr_shape_plan_set_user_data(struct hr_shape_plan_t *shape_plan,
                                      const struct hr_user_data_key_t *key,
                                      void *data,
                                      hr_destroy_func_t destroy,
                                      hr_bool_t replace);

/**
 * Retrieves user data previously attached to a plan.
 *
 * # Safety
 *
 * `shape_plan` must be `NULL` or a live plan.
 */
void *hr_shape_plan_get_user_data(struct hr_shape_plan_t *shape_plan,
                                  const struct hr_user_data_key_t *key);

/**
 * Returns the name of the shaper a plan will use, or `NULL` for the empty
 * plan.
 *
 * # Safety
 *
 * `shape_plan` must be `NULL` or a live plan.
 */
const char *hr_shape_plan_get_shaper(struct hr_shape_plan_t *shape_plan);

/**
 * Writes the properties a plan was built for into `props`.
 *
 * # Safety
 *
 * `shape_plan` must be `NULL` or a live plan, and `props` must be `NULL` or
 * writable.
 */
void hr_shape_plan_get_segment_properties(struct hr_shape_plan_t *shape_plan,
                                          struct hr_segment_properties_t *props);

/**
 * Shapes a buffer using a plan that was built beforehand.
 *
 * Returns false without shaping if the plan is the empty one, or if `font` or
 * `buffer` is `NULL`. An empty buffer returns true, having nothing to do.
 *
 * # Aborts
 *
 * Using a plan that does not apply aborts the process, as HarfBuzz's
 * assertions do: the plan must have been built over the same face, for the
 * same variation settings, and for the direction, script and language the
 * buffer carries. These are programming errors rather than conditions to
 * recover from, and shaping through a mismatched plan yields a wrong answer
 * rather than a slow one. Use `hr_shape` if you would rather have a plan
 * chosen for you.
 *
 * # Safety
 *
 * `shape_plan`, `font` and `buffer` must be `NULL` or live, and `features`
 * must point to `num_features` readable entries.
 */
hr_bool_t hr_shape_plan_execute(struct hr_shape_plan_t *shape_plan,
                                struct hr_font_t *font,
                                struct hr_buffer_t *buffer,
                                const struct hr_feature_t *features,
                                unsigned int num_features);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

/* Convenience macros with no Rust counterpart, matching HarfBuzz's. */

/** Builds a tag from four characters. */
#define HR_TAG(c1, c2, c3, c4) ((hr_tag_t)((((uint32_t) (c1) & 0xFF) << 24) | (((uint32_t) (c2) & 0xFF) << 16) | (((uint32_t) (c3) & 0xFF) << 8) | ((uint32_t) (c4) & 0xFF)))

/** Expands a tag into its four characters, as separate arguments. */
#define HR_UNTAG(tag) (uint8_t)(((tag) >> 24) & 0xFF), (uint8_t)(((tag) >> 16) & 0xFF), (uint8_t)(((tag) >> 8) & 0xFF), (uint8_t)((tag) & 0xFF)

/** An unset language. */
#define HR_LANGUAGE_INVALID ((hr_language_t) 0)

/** Segment properties with every field unset. */
#define HR_SEGMENT_PROPERTIES_DEFAULT { HR_DIRECTION_INVALID, HR_SCRIPT_INVALID, HR_LANGUAGE_INVALID, (void *) 0, (void *) 0 }

/* Spelled as macros because HarfBuzz spells them that way. */
#define HR_DIRECTION_IS_VALID(dir) hr_direction_is_valid(dir)
#define HR_DIRECTION_IS_HORIZONTAL(dir) hr_direction_is_horizontal(dir)
#define HR_DIRECTION_IS_VERTICAL(dir) hr_direction_is_vertical(dir)
#define HR_DIRECTION_IS_FORWARD(dir) hr_direction_is_forward(dir)
#define HR_DIRECTION_IS_BACKWARD(dir) hr_direction_is_backward(dir)
#define HR_DIRECTION_REVERSE(dir) hr_direction_reverse(dir)

/** The version of this library, as a string. */
#define HR_VERSION_STRING "0.13.3"

/** True if this library is at least the given version. */
#define HR_VERSION_ATLEAST(major, minor, micro) ((major) < HR_VERSION_MAJOR || ((major) == HR_VERSION_MAJOR && ((minor) < HR_VERSION_MINOR || ((minor) == HR_VERSION_MINOR && (micro) <= HR_VERSION_MICRO))))
