#!/usr/bin/env python3
"""Generates the core, OpenType and subset HarfBuzz compatibility headers.

The generated header maps every HarfBuzz name onto its HarfRust counterpart,
so that C code written against HarfBuzz's shaping API can be built against
this library by including it in place of <hb.h>.

Every name is taken from hr.h itself, so the two cannot drift apart. Run this
after regenerating hr.h with cbindgen:

    python3 scripts/gen-hb-compat-header.py
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "harfrust_capi", "include", "hr.h")
TARGET = os.path.join(ROOT, "harfrust_capi", "include", "hr-hb.h")
OT_TARGET = os.path.join(ROOT, "harfrust_capi", "include", "hr-hb-ot.h")
SUBSET_SOURCE = os.path.join(ROOT, "harfbuzz_subset_c_api", "include", "hr-subset.h")
SUBSET_TARGET = os.path.join(ROOT, "harfbuzz_subset_c_api", "include", "hr-hb-subset.h")

# Comments hold prose that happens to mention `hr_` names; only declarations
# should contribute mappings.
BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.DOTALL)
LINE_COMMENT = re.compile(r"//[^\n]*")

LOWER = re.compile(r"\bhr_[a-z0-9_]+\b")
UPPER = re.compile(r"\bHR_[A-Z0-9_]+\b")

# Names this library has and HarfBuzz does not. Mapping them would invent
# HarfBuzz spellings: nothing written against HarfBuzz can be using them, and
# anything written against one of them would fail to build against HarfBuzz,
# which is the one thing this header exists to make possible.
HARFRUST_ONLY = {
    # HarfBuzz has no such call: a buffer's clusters are what shaping and
    # `hb_buffer_add_*` make them.
    "hr_buffer_reset_clusters",
    # HarfBuzz keeps a plan's properties to itself.
    "hr_shape_plan_get_segment_properties",
    "hr_harfbuzz_version",
    "hr_harfbuzz_version_atleast",
    "hr_harfbuzz_version_string",
    # HarfBuzz spells these as the upper-case macros, which are mapped below.
    # The functions underneath them are ours.
    "hr_direction_is_backward",
    "hr_direction_is_forward",
    "hr_direction_is_horizontal",
    "hr_direction_is_valid",
    "hr_direction_is_vertical",
    "hr_direction_reverse",
}

HEADER = """\
/* Generated by scripts/gen-hb-compat-header.py from hr.h. Do not edit by hand.
 *
 * HarfBuzz names, mapped onto their HarfRust counterparts. Include this in
 * place of <hb.h> to build code written against the supported HarfBuzz APIs
 * against HarfRust instead:
 *
 *   #include <hr-hb.h>
 *
 *   hb_blob_t *blob = hb_blob_create_from_file("font.ttf");
 *   hb_face_t *face = hb_face_create(blob, 0);
 *   ...
 *
 * Two things to know before reaching for it.
 *
 * This cannot be combined with HarfBuzz itself in one translation unit: the
 * macros below would rewrite HarfBuzz's own declarations. Include one or the
 * other.
 *
 * Shaping, BASE baseline, MATH, CPAL palettes, axis/name metadata, layout lookup, set, map, and OpenType tag
 * conversion APIs are covered.
 * Anything else HarfBuzz offers -- drawing and painting callbacks,
 * subsetting, other layout table introspection, custom Unicode
 * callbacks -- has no mapping here and will fail to compile, which is the
 * point: you find out at build time rather than at run time. OpenType
 * mappings live in hr-hb-ot.h, included here for backward compatibility.
 * HarfBuzz version names report the release matched by shaping; hr_version()
 * and HR_VERSION_* continue to report the HarfRust package version.
 *
 * Behaviour differences that survive the renaming are listed in the README.
 */

#ifndef HARFRUST_HB_H
#define HARFRUST_HB_H

#include "hr.h"
"""


def names(source):
    """Returns the HarfRust identifiers declared in `source`, deduped."""
    stripped = LINE_COMMENT.sub(" ", BLOCK_COMMENT.sub(" ", source))
    lower = sorted(set(LOWER.findall(stripped)) - HARFRUST_ONLY)
    upper = sorted(
        name for name in set(UPPER.findall(stripped))
        if not name.startswith("HR_HARFBUZZ_")
    )
    return lower, upper


def render(lower, upper, header=HEADER):
    out = [header]

    def section(title, entries, max_width=None):
        if not entries:
            return
        out.append("\n/* %s */\n\n" % title)
        width = max(len("hb_" + name[3:]) for name in entries)
        if max_width is not None:
            width = min(width, max_width)
        for name in entries:
            hb = ("hb_" if name.startswith("hr_") else "HB_") + name[3:]
            target = name
            if name.startswith("hr_version"):
                target = name.replace("hr_version", "hr_harfbuzz_version", 1)
            elif name.startswith("HR_VERSION"):
                target = name.replace("HR_VERSION", "HR_HARFBUZZ_VERSION", 1)
            out.append("#define %-*s %s\n" % (width, hb, target))

    # Types and functions share a namespace in C, so one list covers both.
    # Keep existing mappings aligned when a new API name exceeds this column.
    section("Types, functions and callbacks", lower, max_width=48)
    section("Constants and macros", upper, max_width=45)
    return "".join(out)


def main():
    if not os.path.exists(SOURCE):
        sys.exit("%s not found; generate it with cbindgen first" % SOURCE)
    source = open(SOURCE, encoding="utf-8").read()

    lower, upper = names(source)
    ot_lower = [name for name in lower if name.startswith("hr_ot_")]
    ot_upper = [name for name in upper if name.startswith("HR_OT_")]
    lower = [name for name in lower if not name.startswith("hr_ot_")]
    upper = [name for name in upper if not name.startswith("HR_OT_")]
    if not lower or not upper:
        sys.exit("no hr_ names found in %s; has the header changed shape?" % SOURCE)

    with open(TARGET, "w", encoding="utf-8", newline="\n") as f:
        f.write(render(lower, upper))
        f.write('\n/* Kept for existing consumers of the combined compatibility header. */\n'
                '#include "hr-hb-ot.h"\n\n#endif /* HARFRUST_HB_H */\n')

    ot_header = '/* Generated by scripts/gen-hb-compat-header.py. Do not edit by hand. */\n#ifndef HARFRUST_HB_OT_H\n#define HARFRUST_HB_OT_H\n#include "hr-hb.h"\n'
    with open(OT_TARGET, "w", encoding="utf-8", newline="\n") as f:
        f.write(render(ot_lower, ot_upper, ot_header))
        f.write("\n#endif /* HARFRUST_HB_OT_H */\n")

    if os.path.exists(SUBSET_SOURCE):
        subset_header = ('/* Generated by scripts/gen-hb-compat-header.py. Do not edit by hand. */\n'
                         '#ifndef HARFRUST_HB_SUBSET_H\n#define HARFRUST_HB_SUBSET_H\n#include "hr-hb.h"\n#include "hr-subset.h"\n')
        subset_lower, subset_upper = names(open(SUBSET_SOURCE, encoding="utf-8").read())
        with open(SUBSET_TARGET, "w", encoding="utf-8", newline="\n") as f:
            f.write(render(subset_lower, subset_upper, subset_header))
            f.write("\n#endif /* HARFRUST_HB_SUBSET_H */\n")
    print("wrote %s (%d names)" % (TARGET, len(lower) + len(upper)))


if __name__ == "__main__":
    main()
