#!/usr/bin/env python3
"""Generates harfrust-capi/include/hr-hb.h from harfrust-capi/include/hr.h.

The generated header maps every HarfBuzz name onto its HarfRust counterpart,
so that C code written against HarfBuzz's shaping API can be built against
this library by including it in place of <hb.h>.

Every name is taken from hr.h itself, so the two cannot drift apart. Run this
after regenerating hr.h with cbindgen:

    python3 scripts/gen-hb-compat-header.py
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "harfrust-capi", "include", "hr.h")
TARGET = os.path.join(ROOT, "harfrust-capi", "include", "hr-hb.h")

# Comments hold prose that happens to mention `hr_` names; only declarations
# should contribute mappings.
BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.DOTALL)
LINE_COMMENT = re.compile(r"//[^\n]*")

LOWER = re.compile(r"\bhr_[a-z0-9_]+\b")
UPPER = re.compile(r"\bHR_[A-Z0-9_]+\b")

HEADER = """\
/* Generated by scripts/gen-hb-compat-header.py from hr.h. Do not edit by hand.
 *
 * HarfBuzz names, mapped onto their HarfRust counterparts. Include this in
 * place of <hb.h> to build code written against HarfBuzz's shaping API
 * against HarfRust instead:
 *
 *   #include <hr-hb.h>
 *
 *   hb_blob_t *blob = hb_blob_create_from_file("font.ttf");
 *   hb_face_t *face = hb_face_create(blob, 0);
 *   ...
 *
 * Two things to know before reaching for it.
 *
 * This cannot be combined with HarfBuzz itself in one translation unit: the
 * macros below would rewrite HarfBuzz's own declarations. Include one or the
 * other.
 *
 * Only the shaping API is covered, because that is all HarfRust implements.
 * Anything else HarfBuzz offers -- drawing and painting callbacks,
 * subsetting, layout table introspection, hb_set and hb_map, custom Unicode
 * callbacks -- has no mapping here and will fail to compile, which is the
 * point: you find out at build time rather than at run time. The version
 * macros (HB_VERSION_MAJOR and friends) are also absent; call hr_version() or
 * hb_version() instead.
 *
 * Behaviour differences that survive the renaming are listed in the README.
 */

#pragma once

#include "hr.h"
"""


def names(source):
    """Returns the HarfRust identifiers declared in `source`, deduped."""
    stripped = LINE_COMMENT.sub(" ", BLOCK_COMMENT.sub(" ", source))
    lower = sorted(set(LOWER.findall(stripped)))
    upper = sorted(set(UPPER.findall(stripped)))
    return lower, upper


def render(lower, upper):
    out = [HEADER]

    def section(title, entries):
        out.append("\n/* %s */\n\n" % title)
        width = max(len("hb_" + name[3:]) for name in entries)
        for name in entries:
            hb = ("hb_" if name.startswith("hr_") else "HB_") + name[3:]
            out.append("#define %-*s %s\n" % (width, hb, name))

    # Types and functions share a namespace in C, so one list covers both.
    section("Types, functions and callbacks", lower)
    section("Constants and macros", upper)
    return "".join(out)


def main():
    if not os.path.exists(SOURCE):
        sys.exit("%s not found; generate it with cbindgen first" % SOURCE)
    source = open(SOURCE, encoding="utf-8").read()

    lower, upper = names(source)
    if not lower or not upper:
        sys.exit("no hr_ names found in %s; has the header changed shape?" % SOURCE)

    with open(TARGET, "w", encoding="utf-8", newline="\n") as f:
        f.write(render(lower, upper))
    print("wrote %s (%d names)" % (TARGET, len(lower) + len(upper)))


if __name__ == "__main__":
    main()
